krnl: examples/krnldebugled13/krnldebugled13.ino File Reference
krnldebugled13.ino File Reference
#include <krnl.h>
Functions
void t1 ()
void setup ()
void loop ()
void k_breakout ()
Variables
struct k_t * p1
struct k_t * p2
struct k_t * p3
char st1 [100]
char st2 [100]
char st3 [100]
Function Documentation
k_breakout()
void k_breakout ()
Definition at line 54 of file krnldebugled13.ino.
References k_t::nr, and pRun.
loop()
void loop ()
Definition at line 39 of file krnldebugled13.ino.
setup()
void setup ()
Definition at line 23 of file krnldebugled13.ino.
References k_crt_task(), k_init(), k_start(), p1, p2, p3, st1, st2, st3, and t1().
t1()
void t1 ()
Definition at line 11 of file krnldebugled13.ino.
References k_sleep(), k_t::nr, and pRun.
Referenced by setup().
Variable Documentation
p1
struct k_t* p1
Definition at line 5 of file krnldebugled13.ino.
Referenced by setup().
p2
struct k_t * p2
Definition at line 5 of file krnldebugled13.ino.
Referenced by setup().
p3
struct k_t * p3
Definition at line 5 of file krnldebugled13.ino.
Referenced by setup().
st1
char st1[100]
Definition at line 6 of file krnldebugled13.ino.
Referenced by setup().
st2
char st2[100]
Definition at line 6 of file krnldebugled13.ino.
Referenced by setup().
st3
char st3[100]
Definition at line 6 of file krnldebugled13.ino.
Referenced by setup().