krnl: examples/demos-w-analyser/k01/k01.ino File Reference
k01.ino File Reference
#include <krnl.h>
Macros
#define STKSIZE 100
#define TASKPRIO 10
Functions
void task ()
void setup ()
void loop ()
void k_sem_clip (unsigned char nr, int i)
void k_sem_unclip (unsigned char nr)
void k_breakout ()
Variables
char stak [STKSIZE]
struct k_t * pStak
unsigned char led13
Macro Definition Documentation
STKSIZE
#define STKSIZE 100
Definition at line 7 of file k01.ino.
TASKPRIO
#define TASKPRIO 10
Definition at line 9 of file k01.ino.
Function Documentation
k_breakout()
void k_breakout ()
Definition at line 65 of file k01.ino.
References k_t::nr, and pRun.
k_sem_clip()
void k_sem_clip (unsigned char nr, int i)
Definition at line 47 of file k01.ino.
References led13, and k_t::nr.
Referenced by ki_signal().
k_sem_unclip()
void k_sem_unclip (unsigned char nr)
Definition at line 54 of file k01.ino.
References led13, and k_t::nr.
loop()
void loop ()
Definition at line 37 of file k01.ino.
setup()
void setup ()
Definition at line 23 of file k01.ino.
References i, k_crt_task(), k_init(), k_start(), pStak, stak, STKSIZE, task(), and TASKPRIO.
task()
void task ()
Definition at line 14 of file k01.ino.
References k_sleep().
Referenced by setup().
Variable Documentation
led13
unsigned char led13
Definition at line 46 of file k01.ino.
Referenced by k_sem_clip(), and k_sem_unclip().
pStak
struct k_t* pStak
Definition at line 12 of file k01.ino.
Referenced by setup().
stak
char stak[STKSIZE]
Definition at line 11 of file k01.ino.
Referenced by setup().