krnl: examples/krnl1/k01myfirsttask/k01myfirsttask.ino File Reference
k01myfirsttask.ino File Reference
#include <krnl.h>
Macros
#define STK 150
Functions
void t1 ()
void setup ()
void loop ()
void k_breakout ()
Variables
struct k_t * pTask
unsigned char taskStak [STK]
Macro Definition Documentation
STK
#define STK 150
Definition at line 12 of file k01myfirsttask.ino.
Function Documentation
k_breakout()
void k_breakout ()
Definition at line 92 of file k01myfirsttask.ino.
References k_t::nr, and pRun.
loop()
void loop ()
Definition at line 62 of file k01myfirsttask.ino.
setup()
void setup ()
Definition at line 27 of file k01myfirsttask.ino.
References k_crt_task(), k_init(), k_start(), pTask, STK, t1(), and taskStak.
t1()
void t1 ()
Definition at line 15 of file k01myfirsttask.ino.
References cnt, and k_eat_msec().
Referenced by setup().
Variable Documentation
pTask
struct k_t* pTask
Definition at line 9 of file k01myfirsttask.ino.
Referenced by k_crt_task(), and setup().
taskStak
unsigned char taskStak[STK]
Definition at line 13 of file k01myfirsttask.ino.
Referenced by setup().