krnl: examples/krnl1/k03asleep/k03asleep.ino File Reference
k03asleep.ino File Reference
#include <krnl.h>
Macros
#define STK 100
Functions
void t1 ()
void t2 ()
void setup ()
void loop ()
Variables
struct k_t * p1
struct k_t * p2
unsigned char s1 [STK]
unsigned char s2 [STK]
Macro Definition Documentation
STK
#define STK 100
Definition at line 23 of file k03asleep.ino.
Function Documentation
loop()
void loop ()
Definition at line 75 of file k03asleep.ino.
setup()
void setup ()
Definition at line 52 of file k03asleep.ino.
References k_crt_task(), k_init(), k_start(), p1, p2, s1, s2, t1(), and t2().
t1()
void t1 ()
Definition at line 27 of file k03asleep.ino.
References k_eat_msec(), and k_sleep().
Referenced by setup().
t2()
void t2 ()
Definition at line 37 of file k03asleep.ino.
References i, k_eat_msec(), and k_sleep().
Referenced by setup().
Variable Documentation
p1
struct k_t* p1
Definition at line 22 of file k03asleep.ino.
Referenced by setup().
p2
struct k_t * p2
Definition at line 22 of file k03asleep.ino.
Referenced by setup().
s1
unsigned char s1[STK]
Definition at line 25 of file k03asleep.ino.
Referenced by setup().
s2
unsigned char s2[STK]
Definition at line 25 of file k03asleep.ino.
Referenced by setup().