krnl: examples/krnl1/k04periodic/k04periodic.ino File Reference
k04periodic.ino File Reference
#include <krnl.h>
Macros
#define STK 110
Functions
void tperiodic ()
void tnoise ()
void setup ()
void loop ()
void k_breakout ()
Variables
struct k_t * p1
struct k_t * p2
struct k_t * sem1
struct k_t * sem2
char st1 [STK]
char st2 [STK]
int err
Macro Definition Documentation
STK
#define STK 110
Definition at line 4 of file k04periodic.ino.
Function Documentation
k_breakout()
void k_breakout ()
Definition at line 58 of file k04periodic.ino.
References k_t::nr, and pRun.
loop()
void loop ()
Definition at line 53 of file k04periodic.ino.
setup()
void setup ()
Definition at line 31 of file k04periodic.ino.
References err, i, k_crt_sem(), k_crt_task(), k_init(), k_start(), p1, p2, sem1, st1, st2, STK, tnoise(), and tperiodic().
tnoise()
void tnoise ()
Definition at line 21 of file k04periodic.ino.
References k_eat_msec(), and k_sleep().
Referenced by setup().
tperiodic()
void tperiodic ()
Definition at line 9 of file k04periodic.ino.
References k_eat_msec(), k_set_sem_timer(), k_wait(), and sem1.
Referenced by setup().
Variable Documentation
err
int err
Definition at line 29 of file k04periodic.ino.
Referenced by setup().
p1
struct k_t* p1
Definition at line 5 of file k04periodic.ino.
Referenced by setup().
p2
struct k_t * p2
Definition at line 5 of file k04periodic.ino.
Referenced by setup().
sem1
struct k_t * sem1
Definition at line 5 of file k04periodic.ino.
Referenced by setup(), and tperiodic().
sem2
struct k_t * sem2
Definition at line 5 of file k04periodic.ino.
st1
char st1[STK]
Definition at line 7 of file k04periodic.ino.
Referenced by setup().
st2
char st2[STK]
Definition at line 7 of file k04periodic.ino.
Referenced by setup().