krnl: examples/k06syncsem/k06syncsem.ino File Reference
k06syncsem.ino File Reference
#include <krnl.h>
Macros
#define STK 110
Functions
void task1 ()
void task2 ()
void setup ()
void loop ()
void k_breakout ()
Variables
struct k_t * p1
struct k_t * p2
struct k_t * s1
int pendingWait = 0
int loopCnt = 0
int er2
char a1 [STK]
char a2 [STK]
Macro Definition Documentation
STK
#define STK 110
Definition at line 104 of file k06syncsem.ino.
Function Documentation
k_breakout()
void k_breakout ()
Definition at line 141 of file k06syncsem.ino.
References k_t::nr, and pRun.
loop()
void loop ()
Definition at line 137 of file k06syncsem.ino.
setup()
void setup ()
Definition at line 107 of file k06syncsem.ino.
References a1, a2, i, k_crt_sem(), k_crt_task(), k_init(), k_start(), p1, p2, s1, STK, task1(), and task2().
task1()
void task1 ()
Definition at line 43 of file k06syncsem.ino.
References er2, k_eat_msec(), k_set_sem_timer(), k_wait(), loopCnt, and s1.
Referenced by setup().
task2()
void task2 ()
Definition at line 92 of file k06syncsem.ino.
References k_eat_msec(), and k_sleep().
Referenced by setup().
Variable Documentation
a1
char a1[STK]
Definition at line 105 of file k06syncsem.ino.
Referenced by setup().
a2
char a2[STK]
Definition at line 105 of file k06syncsem.ino.
Referenced by setup().
er2
int er2
Definition at line 42 of file k06syncsem.ino.
Referenced by task1().
loopCnt
int loopCnt = 0
Definition at line 40 of file k06syncsem.ino.
Referenced by task1().
p1
struct k_t* p1
Definition at line 37 of file k06syncsem.ino.
Referenced by setup().
p2
struct k_t * p2
Definition at line 37 of file k06syncsem.ino.
Referenced by setup().
pendingWait
int pendingWait = 0
Definition at line 40 of file k06syncsem.ino.
s1
struct k_t * s1
Definition at line 37 of file k06syncsem.ino.
Referenced by setup(), and task1().