krnl: examples/krnl1/krnlsimpledebugled/krnlsimpledebugled.ino File Reference
krnlsimpledebugled.ino File Reference
#include <krnl.h>
Macros
#define STK 110
Functions
void tgeneric ()
void setup ()
void loop ()
void k_breakout ()
Variables
struct k_t * p1
struct k_t * p2
struct k_t * p3
char st1 [STK]
char st2 [STK]
char st3 [STK]
Macro Definition Documentation
STK
#define STK 110
Definition at line 4 of file krnlsimpledebugled.ino.
Function Documentation
k_breakout()
void k_breakout ()
Definition at line 42 of file krnlsimpledebugled.ino.
References k_t::nr, and pRun.
loop()
void loop ()
Definition at line 38 of file krnlsimpledebugled.ino.
setup()
void setup ()
Definition at line 16 of file krnlsimpledebugled.ino.
References i, k_crt_task(), k_init(), k_start(), p1, p2, p3, st1, st2, st3, and tgeneric().
tgeneric()
void tgeneric ()
Definition at line 8 of file krnlsimpledebugled.ino.
References k_eat_msec(), k_sleep(), k_t::nr, and pRun.
Referenced by setup().
Variable Documentation
p1
struct k_t* p1
Definition at line 5 of file krnlsimpledebugled.ino.
Referenced by setup().
p2
struct k_t * p2
Definition at line 5 of file krnlsimpledebugled.ino.
Referenced by setup().
p3
struct k_t * p3
Definition at line 5 of file krnlsimpledebugled.ino.
Referenced by setup().
st1
char st1[STK]
Definition at line 6 of file krnlsimpledebugled.ino.
Referenced by setup().
st2
char st2[STK]
Definition at line 6 of file krnlsimpledebugled.ino.
Referenced by setup().
st3
char st3[STK]
Definition at line 6 of file krnlsimpledebugled.ino.
Referenced by setup().