krnl: examples/oldobsolete/old/akrnlschedule/akrnlschedule.ino File Reference
akrnlschedule.ino File Reference
#include <krnl.h>
Macros
#define TICKSPEED 10
#define STK 100
Functions
void highprio ()
void medprio ()
void lowprio ()
void setup ()
void k_sem_clip (unsigned char nr, int i)
void k_send_Q_clip (unsigned char nr, int i)
void loop ()
Variables
struct k_t * pt1
struct k_t * pt2
struct k_t * pt3
struct k_t * sem1
struct k_t * sem2
struct k_t * sem3
char st1 [STK]
char st2 [STK]
char st3 [STK]
volatile int cnt =0
Macro Definition Documentation
STK
#define STK 100
Definition at line 8 of file akrnlschedule.ino.
TICKSPEED
#define TICKSPEED 10
Definition at line 6 of file akrnlschedule.ino.
Function Documentation
highprio()
void highprio ()
Definition at line 13 of file akrnlschedule.ino.
References k_t::clip, cnt, k_set_sem_timer(), loop(), sem1, and TICKSPEED.
Referenced by setup().
k_sem_clip()
void k_sem_clip (unsigned char nr, int i)
Definition at line 85 of file akrnlschedule.ino.
References cnt.
Referenced by ki_signal().
k_send_Q_clip()
void k_send_Q_clip (unsigned char nr, int i)
Definition at line 91 of file akrnlschedule.ino.
References cnt.
Referenced by ki_send().
loop()
void loop ()
Definition at line 97 of file akrnlschedule.ino.
Referenced by highprio().
lowprio()
void lowprio ()
Definition at line 50 of file akrnlschedule.ino.
References k_t::clip, k_set_sem_timer(), sem3, and TICKSPEED.
Referenced by setup().
medprio()
void medprio ()
Definition at line 37 of file akrnlschedule.ino.
References k_t::clip, k_set_sem_timer(), sem2, and TICKSPEED.
Referenced by setup().
setup()
void setup ()
Definition at line 66 of file akrnlschedule.ino.
References highprio(), k_crt_sem(), k_crt_task(), k_init(), k_start(), lowprio(), medprio(), pt1, pt2, pt3, sem1, sem2, sem3, st1, st2, st3, and STK.
Variable Documentation
cnt
volatile int cnt =0
Definition at line 11 of file akrnlschedule.ino.
Referenced by highprio(), k_sem_clip(), and k_send_Q_clip().
pt1
struct k_t* pt1
Definition at line 3 of file akrnlschedule.ino.
Referenced by setup().
pt2
struct k_t * pt2
Definition at line 3 of file akrnlschedule.ino.
Referenced by setup().
pt3
struct k_t * pt3
Definition at line 3 of file akrnlschedule.ino.
Referenced by setup().
sem1
struct k_t * sem1
Definition at line 3 of file akrnlschedule.ino.
Referenced by highprio(), and setup().
sem2
struct k_t * sem2
Definition at line 3 of file akrnlschedule.ino.
Referenced by medprio(), and setup().
sem3
struct k_t * sem3
Definition at line 3 of file akrnlschedule.ino.
Referenced by lowprio(), and setup().
st1
char st1[STK]
Definition at line 9 of file akrnlschedule.ino.
Referenced by setup().
st2
char st2[STK]
Definition at line 9 of file akrnlschedule.ino.
Referenced by setup().
st3
char st3[STK]
Definition at line 9 of file akrnlschedule.ino.
Referenced by setup().