krnl: examples/oldobsolete/old/ceil04/ceil04.ino File Reference
ceil04.ino File Reference
#include <krnl.h>
Macros
#define STK 150
#define TASKPRIO 10
#define CEIL
Functions
void task1 ()
void task2 ()
void task3 ()
void setup ()
void loop ()
void init_IO_for_debug ()
void bugBitSet (int bitNr)
void bugBitReset (int bitNr)
void k_sem_clip (unsigned char nr, int i)
void k_sem_noclip (unsigned char nr)
void k_breakout ()
Variables
char stak1 [STK]
char stak2 [STK]
char stak3 [STK]
struct k_t * pTask1
struct k_t * pTask2
struct k_t * pTask3
struct k_t * sem1
struct k_t * sem2
struct k_t * sem3
struct k_t * sem4
volatile unsigned char reg = 0
unsigned char led13
Macro Definition Documentation
CEIL
#define CEIL
Definition at line 21 of file ceil04.ino.
STK
#define STK 150
Definition at line 14 of file ceil04.ino.
TASKPRIO
#define TASKPRIO 10
Definition at line 16 of file ceil04.ino.
Function Documentation
bugBitReset()
void bugBitReset (int bitNr)
Definition at line 146 of file ceil04.ino.
References k_t::nr, pRun, and reg.
Referenced by task1(), and task2().
bugBitSet()
void bugBitSet (int bitNr)
Definition at line 129 of file ceil04.ino.
References k_t::nr, pRun, and reg.
Referenced by task1(), and task2().
init_IO_for_debug()
void init_IO_for_debug ()
Definition at line 110 of file ceil04.ino.
References i.
Referenced by setup().
k_breakout()
void k_breakout ()
Definition at line 188 of file ceil04.ino.
References k_t::nr, pRun, and reg.
k_sem_clip()
void k_sem_clip (unsigned char nr, int i)
Definition at line 170 of file ceil04.ino.
References led13, and k_t::nr.
k_sem_noclip()
void k_sem_noclip (unsigned char nr)
!!!
Definition at line 177 of file ceil04.ino.
References led13, and k_t::nr.
loop()
void loop ()
Definition at line 105 of file ceil04.ino.
setup()
void setup ()
Definition at line 82 of file ceil04.ino.
References init_IO_for_debug(), k_crt_sem(), k_crt_task(), k_init(), k_mut_ceil_set(), k_start(), pTask1, pTask2, pTask3, sem1, sem2, sem3, sem4, stak1, stak2, stak3, STK, task1(), task2(), and task3().
task1()
void task1 ()
Definition at line 23 of file ceil04.ino.
References bugBitReset(), bugBitSet(), k_mut_ceil_enter(), k_mut_ceil_leave(), k_set_sem_timer(), k_signal(), k_wait(), sem1, and sem3.
Referenced by setup().
task2()
void task2 ()
Definition at line 45 of file ceil04.ino.
References bugBitReset(), bugBitSet(), k_mut_ceil_enter(), k_mut_ceil_leave(), k_set_sem_timer(), k_signal(), k_wait(), sem1, and sem2.
Referenced by setup().
task3()
void task3 ()
Definition at line 73 of file ceil04.ino.
References k_set_sem_timer(), k_wait(), and sem4.
Referenced by setup().
Variable Documentation
led13
unsigned char led13
Definition at line 168 of file ceil04.ino.
Referenced by k_sem_clip(), and k_sem_noclip().
pTask1
struct k_t* pTask1
Definition at line 19 of file ceil04.ino.
Referenced by setup().
pTask2
struct k_t * pTask2
Definition at line 19 of file ceil04.ino.
Referenced by setup().
pTask3
struct k_t * pTask3
Definition at line 19 of file ceil04.ino.
Referenced by setup().
reg
volatile unsigned char reg = 0
Definition at line 127 of file ceil04.ino.
Referenced by bugBitReset(), bugBitSet(), and k_breakout().
sem1
struct k_t * sem1
Definition at line 19 of file ceil04.ino.
Referenced by setup(), task1(), and task2().
sem2
struct k_t * sem2
Definition at line 19 of file ceil04.ino.
Referenced by setup(), and task2().
sem3
struct k_t * sem3
Definition at line 19 of file ceil04.ino.
Referenced by setup(), and task1().
sem4
struct k_t * sem4
Definition at line 19 of file ceil04.ino.
Referenced by setup(), and task3().
stak1
char stak1[STK]
Definition at line 18 of file ceil04.ino.
Referenced by setup().
stak2
char stak2[STK]
Definition at line 18 of file ceil04.ino.
Referenced by setup().
stak3
char stak3[STK]
Definition at line 18 of file ceil04.ino.
Referenced by setup().