krnl: examples/oldobsolete/old/debug/mutex/mutex.ino File Reference
mutex.ino File Reference
#include <krnl.h>
Data Structures
struct dataTp
Macros
#define STK 100
Functions
void initData ()
void lowTask ()
void controlTask ()
void setup ()
void loop ()
Variables
struct k_t * sem
struct k_t * mutexSem
struct k_t * pT1
struct k_t * pT2
char stakH [STK]
char stakL [STK]
struct dataTp data
Macro Definition Documentation
STK
#define STK 100
Definition at line 5 of file mutex.ino.
Function Documentation
controlTask()
void controlTask ()
Definition at line 38 of file mutex.ino.
References data, dataTp::i, dataTp::j, dataTp::k, k_set_sem_timer(), k_signal(), k_wait(), mutexSem, and sem.
Referenced by setup().
initData()
void initData ()
Definition at line 18 of file mutex.ino.
References data, dataTp::i, dataTp::j, and dataTp::k.
Referenced by setup().
loop()
void loop ()
Definition at line 74 of file mutex.ino.
lowTask()
void lowTask ()
Definition at line 23 of file mutex.ino.
References a, data, dataTp::i, dataTp::j, dataTp::k, k_signal(), k_sleep(), k_wait(), and mutexSem.
Referenced by setup().
setup()
void setup ()
Definition at line 59 of file mutex.ino.
References controlTask(), initData(), k_crt_sem(), k_crt_task(), k_init(), k_start(), lowTask(), mutexSem, pT1, pT2, sem, stakH, stakL, and STK.
Variable Documentation
data
struct dataTp data
Definition at line 15 of file mutex.ino.
Referenced by controlTask(), initData(), and lowTask().
mutexSem
struct k_t * mutexSem
Definition at line 3 of file mutex.ino.
Referenced by controlTask(), lowTask(), and setup().
pT1
struct k_t * pT1
Definition at line 3 of file mutex.ino.
Referenced by setup().
pT2
struct k_t * pT2
Definition at line 3 of file mutex.ino.
Referenced by setup().
sem
struct k_t* sem
Definition at line 3 of file mutex.ino.
Referenced by controlTask(), k_crt_sem(), k_mut_ceil_enter(), k_mut_ceil_leave(), k_mut_ceil_set(), k_sem_signals_lost(), k_semval(), k_set_sem_timer(), k_signal(), k_wait(), k_wait2(), ki_semval(), ki_signal(), ki_wait(), and setup().
stakH
char stakH[STK]
Definition at line 7 of file mutex.ino.
Referenced by setup().
stakL
char stakL[STK]
Definition at line 7 of file mutex.ino.
Referenced by setup().