krnl: examples/oldobsolete/old/debug/msg2/msg2.ino File Reference
msg2.ino File Reference
#include <krnl.h>
Macros
#define STK_SIZE 200
Functions
void doBlink (void)
void t1 (void)
void t2 (void)
void setup ()
void loop (void)
Variables
struct k_t * p_t1
struct k_t * p_t2
struct k_msg_t * pMsg2
char mar2 [10 *2]
char s1 [STK_SIZE]
char s2 [STK_SIZE]
volatile int icnt = 0
Macro Definition Documentation
STK_SIZE
#define STK_SIZE 200
Definition at line 20 of file msg2.ino.
Function Documentation
doBlink()
void doBlink (void)
Definition at line 28 of file msg2.ino.
Referenced by t1().
loop()
void loop (void)
Definition at line 78 of file msg2.ino.
setup()
void setup ()
Definition at line 54 of file msg2.ino.
References k_crt_send_Q(), k_crt_task(), k_init(), k_start(), KRNL_VRS, mar2, p_t1, p_t2, pMsg2, s1, s2, STK_SIZE, t1(), and t2().
t1()
void t1 (void)
Definition at line 34 of file msg2.ino.
References doBlink(), i, k_receive(), and pMsg2.
Referenced by setup().
t2()
void t2 (void)
Definition at line 44 of file msg2.ino.
References i, k_send(), k_sleep(), and pMsg2.
Referenced by setup().
Variable Documentation
icnt
volatile int icnt = 0
Definition at line 25 of file msg2.ino.
mar2
char mar2[10 *2]
Definition at line 18 of file msg2.ino.
Referenced by setup().
p_t1
struct k_t* p_t1
Definition at line 15 of file msg2.ino.
Referenced by setup().
p_t2
struct k_t * p_t2
Definition at line 15 of file msg2.ino.
Referenced by setup().
pMsg2
struct k_msg_t* pMsg2
Definition at line 16 of file msg2.ino.
Referenced by setup(), t1(), and t2().
s1
char s1[STK_SIZE]
Definition at line 22 of file msg2.ino.
Referenced by setup().
s2
char s2[STK_SIZE]
Definition at line 23 of file msg2.ino.
Referenced by setup().