krnl: examples/oldobsolete/old/isrmsgsend/isrmsgsend.ino File Reference
isrmsgsend.ino File Reference
#include <krnlt.h>
Macros
#define STK_SIZE 200
Functions
void t1 (void)
void t2 (void)
ISR (INT0_vect, ISR_NAKED)
void setup ()
void loop (void)
Variables
struct k_t * tSm1
struct k_t * tSm2
struct k_t * p_t1
struct k_t * p_t2
struct k_msg_t * pMsg
char mar [10 *2]
char s1 [STK_SIZE]
char s2 [STK_SIZE]
volatile int icnt =0
Macro Definition Documentation
STK_SIZE
#define STK_SIZE 200
Definition at line 21 of file isrmsgsend.ino.
Function Documentation
ISR()
ISR (INT0_vect , ISR_NAKED)
Definition at line 60 of file isrmsgsend.ino.
References icnt, K_CHG_STAK, k_running, ki_send(), pMsg, PUSHREGS(), and RETI().
loop()
void loop (void)
Definition at line 117 of file isrmsgsend.ino.
setup()
void setup ()
Definition at line 77 of file isrmsgsend.ino.
References k_crt_sem(), k_crt_send_Q(), k_crt_task(), k_init(), k_start(), mar, p_t1, p_t2, pMsg, s1, s2, STK_SIZE, t1(), t2(), tSm1, and tSm2.
t1()
void t1 (void)
Definition at line 29 of file isrmsgsend.ino.
References k_signal(), and tSm2.
Referenced by setup().
t2()
void t2 (void)
Definition at line 37 of file isrmsgsend.ino.
References i, k_receive(), k_set_sem_timer(), k_wait(), pMsg, and tSm2.
Referenced by setup().
Variable Documentation
icnt
volatile int icnt =0
Definition at line 26 of file isrmsgsend.ino.
Referenced by ISR().
mar
char mar[10 *2]
Definition at line 19 of file isrmsgsend.ino.
Referenced by setup().
p_t1
struct k_t* p_t1
Definition at line 16 of file isrmsgsend.ino.
Referenced by setup().
p_t2
struct k_t * p_t2
Definition at line 16 of file isrmsgsend.ino.
Referenced by setup().
pMsg
struct k_msg_t* pMsg
Definition at line 18 of file isrmsgsend.ino.
Referenced by ISR(), setup(), and t2().
s1
char s1[STK_SIZE]
Definition at line 23 of file isrmsgsend.ino.
Referenced by setup().
s2
char s2[STK_SIZE]
Definition at line 24 of file isrmsgsend.ino.
Referenced by setup().
tSm1
struct k_t* tSm1
Definition at line 15 of file isrmsgsend.ino.
Referenced by setup().
tSm2
struct k_t * tSm2
Definition at line 15 of file isrmsgsend.ino.
Referenced by setup(), t1(), and t2().