krnl: examples/nokrnl/obsolete/k000time02/k000time02.ino File Reference
k000time02.ino File Reference
Functions
void setup ()
void controlCode ()
int kicker (void(*f)(), unsigned long *t, unsigned long per)
void loop ()
Variables
const unsigned long Tper = 100
int tMin =10
int tMax = 95
volatile unsigned long nextTimeToRun = 0
Function Documentation
controlCode()
void controlCode ()
Definition at line 14 of file k000time02.ino.
References tMax, and tMin.
Referenced by loop().
kicker()
int kicker (void(*)() f, unsigned long * t, unsigned long per)
Definition at line 19 of file k000time02.ino.
References t.
Referenced by loop().
loop()
void loop ()
Definition at line 32 of file k000time02.ino.
References controlCode(), kicker(), nextTimeToRun, and Tper.
setup()
void setup ()
Definition at line 3 of file k000time02.ino.
Variable Documentation
nextTimeToRun
volatile unsigned long nextTimeToRun = 0
Definition at line 11 of file k000time02.ino.
Referenced by loop().
tMax
int tMax = 95
Definition at line 9 of file k000time02.ino.
Referenced by controlCode().
tMin
int tMin =10
Definition at line 9 of file k000time02.ino.
Referenced by controlCode().
Tper
const unsigned long Tper = 100
Definition at line 7 of file k000time02.ino.
Referenced by loop().