krnl: examples/nokrnl/obsolete/k000time03/k000time03.ino File Reference
k000time03.ino File Reference
Macros
#define DEBUG
#define BUGPRINTLN(x) Serial.println(x)
Functions
void setup ()
void controlCode ()
int testCloseToLimit (int id, unsigned int nTime, unsigned long limit)
int kicker (void(*f)(), unsigned long *t, unsigned long per)
void loop ()
Variables
const unsigned long Tper = 100
volatile unsigned long nextTimeToRun = 0
volatile unsigned long timeToDelay
unsigned long limit = 30
Macro Definition Documentation
BUGPRINTLN
#define BUGPRINTLN (x) Serial.println(x)
Definition at line 7 of file k000time03.ino.
DEBUG
#define DEBUG
Definition at line 4 of file k000time03.ino.
Function Documentation
controlCode()
void controlCode ()
Definition at line 22 of file k000time03.ino.
Referenced by loop().
kicker()
int kicker (void(*)() f, unsigned long * t, unsigned long per)
Definition at line 46 of file k000time03.ino.
References BUGPRINTLN, and t.
Referenced by loop().
loop()
void loop ()
Definition at line 59 of file k000time03.ino.
References controlCode(), kicker(), limit, nextTimeToRun, testCloseToLimit(), and Tper.
setup()
void setup ()
Definition at line 12 of file k000time03.ino.
testCloseToLimit()
int testCloseToLimit (int id, unsigned int nTime, unsigned long limit)
Definition at line 27 of file k000time03.ino.
References limit.
Referenced by loop().
Variable Documentation
limit
unsigned long limit = 30
Definition at line 20 of file k000time03.ino.
Referenced by loop(), and testCloseToLimit().
nextTimeToRun
volatile unsigned long nextTimeToRun = 0
Definition at line 18 of file k000time03.ino.
Referenced by loop().
timeToDelay
volatile unsigned long timeToDelay
Definition at line 18 of file k000time03.ino.
Tper
const unsigned long Tper = 100
Definition at line 16 of file k000time03.ino.
Referenced by loop().