krnl: examples/nokrnl/obsolete/k000time5/k000time5.ino File Reference
k000time5.ino File Reference
Functions
void setup ()
void controlCode1 ()
void controlCode2 ()
int testCloseToLimit (int id, unsigned int nTime, unsigned long limit)
int kicker (void(*f)(), unsigned long *t, unsigned long per)
void loop ()
Variables
volatile unsigned long nextTimeToRun1 = 0
volatile unsigned long nextTimeToRun2 = 0
const unsigned long tPer1 = 300
const unsigned long tPer2 = 500
const unsigned int tGap1 = 200
const unsigned int tGap2 = 15
int tLow1 = 10
int tHigh1 = 150
int tLow2 = 10
int tHigh2 = 400
Function Documentation
controlCode1()
void controlCode1 ()
Definition at line 18 of file k000time5.ino.
References tHigh1, and tLow1.
Referenced by loop().
controlCode2()
void controlCode2 ()
Definition at line 24 of file k000time5.ino.
References tHigh2, and tLow2.
Referenced by loop().
kicker()
int kicker (void(*)() f, unsigned long * t, unsigned long per)
Definition at line 59 of file k000time5.ino.
References t.
Referenced by loop().
loop()
void loop ()
Definition at line 72 of file k000time5.ino.
References controlCode1(), controlCode2(), kicker(), nextTimeToRun1, nextTimeToRun2, testCloseToLimit(), tGap1, tGap2, tPer1, and tPer2.
setup()
void setup ()
Definition at line 5 of file k000time5.ino.
testCloseToLimit()
int testCloseToLimit (int id, unsigned int nTime, unsigned long limit)
Definition at line 30 of file k000time5.ino.
References limit.
Referenced by loop().
Variable Documentation
nextTimeToRun1
volatile unsigned long nextTimeToRun1 = 0
Definition at line 9 of file k000time5.ino.
Referenced by loop().
nextTimeToRun2
volatile unsigned long nextTimeToRun2 = 0
Definition at line 9 of file k000time5.ino.
Referenced by loop().
tGap1
const unsigned int tGap1 = 200
Definition at line 12 of file k000time5.ino.
Referenced by loop().
tGap2
const unsigned int tGap2 = 15
Definition at line 12 of file k000time5.ino.
Referenced by loop().
tHigh1
int tHigh1 = 150
Definition at line 15 of file k000time5.ino.
Referenced by controlCode1().
tHigh2
int tHigh2 = 400
Definition at line 17 of file k000time5.ino.
Referenced by controlCode2().
tLow1
int tLow1 = 10
Definition at line 14 of file k000time5.ino.
Referenced by controlCode1().
tLow2
int tLow2 = 10
Definition at line 16 of file k000time5.ino.
Referenced by controlCode2().
tPer1
const unsigned long tPer1 = 300
Definition at line 11 of file k000time5.ino.
Referenced by loop().
tPer2
const unsigned long tPer2 = 500
Definition at line 11 of file k000time5.ino.
Referenced by loop().