krnl: examples/oldobsolete/old/k001timertest/k001timertest.ino File Reference
k001timertest.ino File Reference
#include <i2a.h>
#include <krnl.h>
Functions
void test (int msec)
void ktest (int msec)
void t1 ()
void setup ()
void loop ()
Variables
char a [10]
char s1 [100]
Function Documentation
ktest()
void ktest (int msec)
Definition at line 172 of file k001timertest.ino.
References a, t1(), and t2.
Referenced by setup(), and t1().
loop()
void loop ()
Definition at line 211 of file k001timertest.ino.
setup()
void setup ()
Definition at line 198 of file k001timertest.ino.
References i, k_crt_task(), k_init(), k_start(), ktest(), s1, t1(), and test().
t1()
void t1 ()
Definition at line 187 of file k001timertest.ino.
References i, ktest(), and test().
Referenced by ktest(), setup(), and test().
test()
void test (int msec)
Definition at line 152 of file k001timertest.ino.
References a, t1(), and t2.
Referenced by setup(), and t1().
Variable Documentation
a
char a[10]
Definition at line 150 of file k001timertest.ino.
Referenced by ktest(), and test().
s1
char s1[100]
Definition at line 186 of file k001timertest.ino.
Referenced by setup().