krnl: examples/oldobsolete/k015priority/k015priority.ino File Reference
k015priority.ino File Reference
#include <krnl.h>
Functions
void t1 ()
void t2 ()
void setup ()
void loop ()
Variables
struct k_t * p1
struct k_t * p2
struct k_t * s1
Function Documentation
loop()
void loop ()
Definition at line 54 of file k015priority.ino.
setup()
void setup ()
Definition at line 30 of file k015priority.ino.
References k_crt_sem(), k_crt_task(), k_init(), k_start(), p1, p2, s1, t1(), and t2().
t1()
void t1 ()
Definition at line 10 of file k015priority.ino.
References k_eat_ticks(), k_set_sem_timer(), k_wait(), and s1.
Referenced by setup().
t2()
void t2 ()
Definition at line 21 of file k015priority.ino.
References i.
Referenced by setup().
Variable Documentation
p1
struct k_t* p1
Definition at line 6 of file k015priority.ino.
Referenced by setup().
p2
struct k_t * p2
Definition at line 6 of file k015priority.ino.
Referenced by setup().
s1
struct k_t * s1
Definition at line 6 of file k015priority.ino.
Referenced by setup(), and t1().