krnl: examples/oldobsolete/old/k01debug/k01debug.ino File Reference
k01debug.ino File Reference
#include <krnl.h>
Macros
#define STKSIZE 100
#define TASKPRIO 10
Functions
void task ()
void setup ()
void loop ()
void k_sem_clip (unsigned char nr, int i)
void k_sem_noclip (unsigned char nr)
void k_breakout ()
Variables
char stak [STKSIZE]
struct k_t * pStak
unsigned char led13
Macro Definition Documentation
STKSIZE
#define STKSIZE 100
Definition at line 7 of file k01debug.ino.
TASKPRIO
#define TASKPRIO 10
Definition at line 9 of file k01debug.ino.
Function Documentation
k_breakout()
void k_breakout ()
Definition at line 74 of file k01debug.ino.
References k_t::nr, and pRun.
k_sem_clip()
void k_sem_clip (unsigned char nr, int i)
Definition at line 56 of file k01debug.ino.
References led13, and k_t::nr.
k_sem_noclip()
void k_sem_noclip (unsigned char nr)
Definition at line 63 of file k01debug.ino.
References led13, and k_t::nr.
loop()
void loop ()
Definition at line 46 of file k01debug.ino.
setup()
void setup ()
Definition at line 32 of file k01debug.ino.
References i, k_crt_task(), k_init(), k_start(), pStak, stak, STKSIZE, task(), and TASKPRIO.
task()
void task ()
Definition at line 14 of file k01debug.ino.
References k_eat_msec_time, and k_sleep().
Referenced by setup().
Variable Documentation
led13
unsigned char led13
Definition at line 55 of file k01debug.ino.
Referenced by k_sem_clip(), and k_sem_noclip().
pStak
struct k_t* pStak
Definition at line 12 of file k01debug.ino.
Referenced by setup().
stak
char stak[STKSIZE]
Definition at line 11 of file k01debug.ino.
Referenced by setup().