krnl: examples/oldobsolete/k012twotasks/k01twotasks.ino File Reference
k01twotasks.ino File Reference
#include <krnl.h>
Functions
void t1 ()
void t2 ()
void setup ()
void loop ()
Variables
struct k_t * p1
struct k_t * p2
Function Documentation
loop()
void loop ()
Definition at line 49 of file k01twotasks.ino.
setup()
void setup ()
Definition at line 28 of file k01twotasks.ino.
References k_crt_task(), k_init(), k_start(), p1, p2, t1(), and t2().
t1()
void t1 ()
Definition at line 7 of file k01twotasks.ino.
References k_sleep().
Referenced by setup().
t2()
void t2 ()
Definition at line 18 of file k01twotasks.ino.
References i, and k_sleep().
Referenced by setup().
Variable Documentation
p1
struct k_t* p1
Definition at line 5 of file k01twotasks.ino.
Referenced by setup().
p2
struct k_t * p2
Definition at line 5 of file k01twotasks.ino.
Referenced by setup().