dit projekt: examples/demos-w-analyser/k02/k02.ino File Reference
k02.ino File Reference
#include <krnl.h>
Macros
#define STKSIZE 100
#define TASKPRIO 10
Functions
void task ()
void task2 ()
void setup ()
void loop ()
void k_sem_clip (unsigned char nr, int i)
void k_sem_unclip (unsigned char nr)
void k_breakout ()
Variables
char stak [STKSIZE]
char stak2 [STKSIZE]
struct k_t * pTask
struct k_t * pTask2
unsigned char led13
Macro Definition Documentation
STKSIZE
#define STKSIZE 100
Definition at line 8 of file k02.ino.
TASKPRIO
#define TASKPRIO 10
Definition at line 10 of file k02.ino.
Function Documentation
k_breakout()
void k_breakout ()
Definition at line 78 of file k02.ino.
References k_t::nr, and pRun.
k_sem_clip()
void k_sem_clip (unsigned char nr, int i)
Definition at line 60 of file k02.ino.
References led13, and k_t::nr.
Referenced by ki_signal().
k_sem_unclip()
void k_sem_unclip (unsigned char nr)
Definition at line 67 of file k02.ino.
References led13, and k_t::nr.
loop()
void loop ()
Definition at line 50 of file k02.ino.
setup()
void setup ()
Definition at line 35 of file k02.ino.
References i, k_crt_task(), k_init(), k_start(), pTask, pTask2, stak, stak2, STKSIZE, task(), task2(), and TASKPRIO.
task()
void task ()
Definition at line 15 of file k02.ino.
Referenced by setup().
task2()
void task2 ()
Definition at line 25 of file k02.ino.
Referenced by setup().
Variable Documentation
led13
unsigned char led13
Definition at line 59 of file k02.ino.
Referenced by k_sem_clip(), and k_sem_unclip().
pTask
struct k_t * pTask
Definition at line 13 of file k02.ino.
Referenced by k_crt_task(), and setup().
pTask2
struct k_t * pTask2
Definition at line 13 of file k02.ino.
Referenced by setup().
stak
char stak
Definition at line 12 of file k02.ino.
Referenced by setup().
stak2
unsigned char stak2
Definition at line 12 of file k02.ino.
Referenced by setup().