dit projekt: examples/k02twotasks/k02twotasks.ino File Reference
k02twotasks.ino File Reference
#include <krnl.h>
Functions
void sampl ()
void alg01 ()
void aktuer01 ()
void t1 (void)
void t2 ()
void setup ()
void loop ()
void k_breakout ()
Variables
const int STKSZ = 200
struct k_t * pt1
struct k_t * pt2
char stak1 [STKSZ]
char stak2 [STKSZ]
int loopNr = 0
volatile int i = 1000
Function Documentation
aktuer01()
void aktuer01 ()
Definition at line 17 of file k02twotasks.ino.
References loopNr.
Referenced by t1().
alg01()
void alg01 ()
Definition at line 13 of file k02twotasks.ino.
Referenced by t1().
k_breakout()
void k_breakout ()
Definition at line 86 of file k02twotasks.ino.
References k_t::nr, and pRun.
loop()
void loop ()
Definition at line 78 of file k02twotasks.ino.
sampl()
void sampl ()
Definition at line 11 of file k02twotasks.ino.
Referenced by t1().
setup()
void setup ()
Definition at line 47 of file k02twotasks.ino.
References k_crt_task(), k_init(), k_start(), pt1, pt2, stak1, stak2, STKSZ, t1(), and t2().
t1()
void t1 (void)
dette er en test
Definition at line 28 of file k02twotasks.ino.
References aktuer01(), alg01(), k_eat_msec(), k_sleep(), and sampl().
Referenced by setup().
t2()
void t2 ()
Definition at line 40 of file k02twotasks.ino.
References k_sleep().
Referenced by setup().
Variable Documentation
i
volatile int i = 1000
Definition at line 24 of file k02twotasks.ino.
Referenced by k_crt_task(), k_receive(), k_set_prio(), k_unused_stak(), ki_receive(), ki_send(), setup(), t2(), and task1().
loopNr
int loopNr = 0
Definition at line 15 of file k02twotasks.ino.
Referenced by aktuer01().
pt1
struct k_t* pt1
Definition at line 6 of file k02twotasks.ino.
Referenced by setup().
pt2
struct k_t * pt2
Definition at line 7 of file k02twotasks.ino.
Referenced by setup().
stak1
char stak1[STKSZ]
Definition at line 9 of file k02twotasks.ino.
Referenced by setup().
stak2
char stak2[STKSZ]
Definition at line 9 of file k02twotasks.ino.
Referenced by setup().
STKSZ
const int STKSZ = 200
Definition at line 4 of file k02twotasks.ino.
Referenced by setup().