krnl: examples/krnl1/k03priorityequalfixed/k03priorityequalfixed.ino File Reference
k03priorityequalfixed.ino File Reference
#include <krnl.h>
Macros
#define SS 100
Functions
void t1 ()
void t2 ()
void setup ()
void loop ()
Variables
struct k_t * p1
struct k_t * p2
unsigned char s1 [SS]
unsigned char s2 [SS]
Macro Definition Documentation
SS
#define SS 100
Definition at line 15 of file k03priorityequalfixed.ino.
Function Documentation
loop()
void loop ()
Definition at line 69 of file k03priorityequalfixed.ino.
setup()
void setup ()
Definition at line 46 of file k03priorityequalfixed.ino.
References k_crt_task(), k_init(), k_start(), p1, p2, s1, s2, t1(), and t2().
t1()
void t1 ()
Definition at line 19 of file k03priorityequalfixed.ino.
References k_sleep().
Referenced by setup().
t2()
void t2 ()
Definition at line 28 of file k03priorityequalfixed.ino.
References i, k_millis(), and k_sleep().
Referenced by setup().
Variable Documentation
p1
struct k_t* p1
Definition at line 13 of file k03priorityequalfixed.ino.
Referenced by setup().
p2
struct k_t * p2
Definition at line 13 of file k03priorityequalfixed.ino.
Referenced by setup().
s1
unsigned char s1[SS]
Definition at line 16 of file k03priorityequalfixed.ino.
Referenced by setup().
s2
unsigned char s2[SS]
Definition at line 16 of file k03priorityequalfixed.ino.
Referenced by setup().