krnl: examples/oldobsolete/old/k04mutex/k04mutex.ino File Reference
k04mutex.ino File Reference
#include <krnl.h>
Functions
void toggleLED13 ()
void setup ()
void loop ()
Variables
struct k_t * pt1
struct k_t * pt2
struct k_t * mutexSem
char s1 [200]
char s2 [200]
Function Documentation
loop()
void loop ()
Definition at line 52 of file k04mutex.ino.
setup()
void setup ()
Definition at line 29 of file k04mutex.ino.
References k_crt_sem(), k_crt_task(), k_init(), k_start(), mutexSem, pt1, pt2, s1, s2, t1, and t2.
toggleLED13()
void toggleLED13 ()
Definition at line 15 of file k04mutex.ino.
Variable Documentation
mutexSem
struct k_t * mutexSem
Definition at line 10 of file k04mutex.ino.
Referenced by setup().
pt1
struct k_t* pt1
Definition at line 8 of file k04mutex.ino.
Referenced by setup().
pt2
struct k_t * pt2
Definition at line 9 of file k04mutex.ino.
Referenced by setup().
s1
char s1[200]
Definition at line 12 of file k04mutex.ino.
Referenced by setup().
s2
char s2[200]
Definition at line 13 of file k04mutex.ino.
Referenced by setup().