dit projekt: examples/demos-w-analyser/k07/k07.ino File Reference
k07.ino File Reference
#include <krnl.h>
Macros
#define STKSIZE 110
#define TASKPRIO 10
Functions
void task ()
void task2 ()
void setup ()
void loop ()
void k_sem_clip (unsigned char nr, int i)
void k_sem_unclip (unsigned char nr)
void k_breakout ()
Variables
char stak [STKSIZE]
char stak2 [STKSIZE]
struct k_t * pTask
struct k_t * pTask2
struct k_t * sem1
volatile char reg = 0
unsigned char led13
Macro Definition Documentation
STKSIZE
#define STKSIZE 110
Definition at line 10 of file k07.ino.
TASKPRIO
#define TASKPRIO 10
Definition at line 12 of file k07.ino.
Function Documentation
k_breakout()
void k_breakout ()
Definition at line 115 of file k07.ino.
References k_t::nr, pRun, and reg.
k_sem_clip()
void k_sem_clip (unsigned char nr, int i)
Definition at line 97 of file k07.ino.
References led13, and k_t::nr.
k_sem_unclip()
void k_sem_unclip (unsigned char nr)
Definition at line 104 of file k07.ino.
References led13, and k_t::nr.
loop()
void loop ()
Definition at line 86 of file k07.ino.
setup()
void setup ()
Definition at line 69 of file k07.ino.
References i, k_crt_sem(), k_crt_task(), k_init(), k_start(), pTask, pTask2, sem1, stak, stak2, STKSIZE, task(), task2(), and TASKPRIO.
task()
void task ()
Definition at line 19 of file k07.ino.
References k_eat_msec(), k_signal(), k_sleep(), k_wait(), k_t::nr, pRun, reg, and sem1.
Referenced by setup().
task2()
void task2 ()
Definition at line 44 of file k07.ino.
References k_eat_msec(), k_signal(), k_sleep(), k_wait(), k_t::nr, pRun, reg, and sem1.
Referenced by setup().
Variable Documentation
led13
unsigned char led13
Definition at line 95 of file k07.ino.
Referenced by k_sem_clip(), and k_sem_unclip().
pTask
struct k_t* pTask
Definition at line 15 of file k07.ino.
Referenced by setup().
pTask2
struct k_t * pTask2
Definition at line 15 of file k07.ino.
Referenced by setup().
reg
volatile char reg = 0
Definition at line 17 of file k07.ino.
Referenced by k_breakout(), task(), and task2().
sem1
struct k_t * sem1
Definition at line 15 of file k07.ino.
Referenced by setup(), task(), and task2().
stak
char stak[STKSIZE]
Definition at line 14 of file k07.ino.
Referenced by setup().
stak2
char stak2[STKSIZE]
Definition at line 14 of file k07.ino.
Referenced by setup().