krnl: examples/krnl2/k07mutexsem/k07mutexsem.ino File Reference
k07mutexsem.ino File Reference
#include <krnl.h>
Data Structures
struct shDataTp
Functions
void saveDataInCritRegion (int v)
struct shDataTp getDataInCritRegion (void)
void t1 ()
void t2 ()
void setup ()
void loop ()
Variables
struct k_t * p1
struct k_t * p2
struct k_t * s1
struct k_t * semmutex
struct shDataTp sharedData = {0, 0}
char a1 [100]
char a2 [100]
Function Documentation
getDataInCritRegion()
struct shDataTp getDataInCritRegion (void)
Definition at line 25 of file k07mutexsem.ino.
References shDataTp::counter, k_signal(), k_wait(), semmutex, and sharedData.
Referenced by t2().
loop()
void loop ()
Definition at line 92 of file k07mutexsem.ino.
saveDataInCritRegion()
void saveDataInCritRegion (int v)
Definition at line 15 of file k07mutexsem.ino.
References shDataTp::counter, k_signal(), k_wait(), semmutex, sharedData, and shDataTp::v.
Referenced by t1().
setup()
void setup ()
Definition at line 67 of file k07mutexsem.ino.
References a1, a2, k_crt_sem(), k_crt_task(), k_init(), k_start(), p1, p2, s1, semmutex, t1(), and t2().
t1()
void t1 ()
Definition at line 38 of file k07mutexsem.ino.
References k_set_sem_timer(), k_wait(), s1, saveDataInCritRegion(), and shDataTp::v.
Referenced by setup().
t2()
void t2 ()
Definition at line 51 of file k07mutexsem.ino.
References getDataInCritRegion(), k_sleep(), and shDataTp::v.
Referenced by setup().
Variable Documentation
a1
char a1[100]
Definition at line 65 of file k07mutexsem.ino.
Referenced by setup().
a2
char a2[100]
Definition at line 65 of file k07mutexsem.ino.
Referenced by setup().
p1
struct k_t* p1
Definition at line 5 of file k07mutexsem.ino.
Referenced by setup().
p2
struct k_t * p2
Definition at line 5 of file k07mutexsem.ino.
Referenced by setup().
s1
struct k_t * s1
Definition at line 5 of file k07mutexsem.ino.
Referenced by setup(), and t1().
semmutex
struct k_t * semmutex
Definition at line 5 of file k07mutexsem.ino.
Referenced by getDataInCritRegion(), saveDataInCritRegion(), and setup().
sharedData
struct shDataTp sharedData = {0, 0}
Definition at line 13 of file k07mutexsem.ino.
Referenced by getDataInCritRegion(), and saveDataInCritRegion().