krnl: examples/krnl3/k08isrsem/k08isrsem.ino File Reference
k08isrsem.ino File Reference
#include <krnl.h>
Macros
#define STK 150
#define TASKPRIO 10
Functions
PUSHREGS ()
if (!k_running) goto exitt
if (-1==ki_signal(syncSem)) ISRoverflow++
K_CHG_STAK ()
RETI ()
void task1 ()
void setup ()
void loop ()
Variables
struct k_t * pTask1
struct k_t * mutSem
struct k_t * syncSem
struct k_t * timedSem1
struct k_t * timedSem2
volatile int t2Missed = 0
volatile int t2Hit = 0
volatile int ISRoverflow = 0
exitt __pad1__
achar a [STK]
Macro Definition Documentation
STK
#define STK 150
Definition at line 10 of file k08isrsem.ino.
TASKPRIO
#define TASKPRIO 10
Definition at line 12 of file k08isrsem.ino.
Function Documentation
if() [1/2]
if (! k_running)
Definition at line 364 of file krnl.c.
if() [2/2]
if (- 1 = =ki_signal(syncSem))
K_CHG_STAK()
K_CHG_STAK ()
loop()
void loop ()
Definition at line 125 of file k08isrsem.ino.
PUSHREGS()
PUSHREGS ()
RETI()
RETI ()
setup()
void setup ()
Definition at line 77 of file k08isrsem.ino.
References k_crt_sem(), k_crt_task(), k_init(), k_start(), k_t::maxv, pTask1, STK, syncSem, and task1().
task1()
void task1 ()
Definition at line 50 of file k08isrsem.ino.
References i, ISRoverflow, k_wait2(), and syncSem.
Referenced by setup().
Variable Documentation
__pad1__
exitt __pad1__
Definition at line 45 of file k08isrsem.ino.
a
achar a[STK]
Definition at line 74 of file k08isrsem.ino.
ISRoverflow
volatile int ISRoverflow = 0
Definition at line 24 of file k08isrsem.ino.
Referenced by task1().
mutSem
struct k_t* mutSem
Definition at line 17 of file k08isrsem.ino.
pTask1
struct k_t* pTask1
Definition at line 15 of file k08isrsem.ino.
Referenced by setup().
syncSem
struct k_t * syncSem
Definition at line 17 of file k08isrsem.ino.
Referenced by setup(), and task1().
t2Hit
volatile int t2Hit = 0
Definition at line 21 of file k08isrsem.ino.
t2Missed
volatile int t2Missed = 0
Definition at line 21 of file k08isrsem.ino.
timedSem1
struct k_t* timedSem1
Definition at line 19 of file k08isrsem.ino.
timedSem2
struct k_t * timedSem2
Definition at line 19 of file k08isrsem.ino.