krnl: examples/krnl2/k09msgq/k09msgq.ino File Reference
k09msgq.ino File Reference
#include <krnl.h>
Macros
#define STK 150
#define TASKPRIO 10
Functions
void task1 ()
void task2 ()
void setup ()
void loop ()
Variables
struct k_t * pTask1
struct k_t * pTask2
struct k_msg_t * msgQ
int dataBufForMsgQ [10]
struct k_t * timedSem1
struct k_t * timedSem2
struct k_t * mutSem
volatile int t2Missed = 0
volatile int t2Hit = 0
char a1 [STK]
char a2 [STK]
Macro Definition Documentation
STK
#define STK 150
Definition at line 7 of file k09msgq.ino.
TASKPRIO
#define TASKPRIO 10
Definition at line 9 of file k09msgq.ino.
Function Documentation
loop()
void loop ()
Definition at line 110 of file k09msgq.ino.
setup()
void setup ()
Definition at line 85 of file k09msgq.ino.
References a1, a2, dataBufForMsgQ, k_crt_sem(), k_crt_send_Q(), k_crt_task(), k_init(), k_start(), msgQ, mutSem, pTask1, pTask2, STK, task1(), task2(), timedSem1, and timedSem2.
task1()
void task1 ()
Definition at line 26 of file k09msgq.ino.
References i, k_eat_ticks(), k_send(), k_set_sem_timer(), k_signal(), k_wait(), msgQ, mutSem, and timedSem1.
Referenced by setup().
task2()
void task2 ()
Definition at line 57 of file k09msgq.ino.
References k_receive(), k_set_sem_timer(), k_signal(), k_wait(), msgQ, mutSem, and timedSem2.
Referenced by setup().
Variable Documentation
a1
char a1[STK]
Definition at line 20 of file k09msgq.ino.
Referenced by setup().
a2
char a2[STK]
Definition at line 24 of file k09msgq.ino.
Referenced by setup().
dataBufForMsgQ
int dataBufForMsgQ[10]
Definition at line 16 of file k09msgq.ino.
Referenced by setup().
msgQ
struct k_msg_t* msgQ
Definition at line 14 of file k09msgq.ino.
Referenced by setup(), task1(), and task2().
mutSem
struct k_t * mutSem
Definition at line 18 of file k09msgq.ino.
Referenced by setup(), task1(), and task2().
pTask1
struct k_t* pTask1
Definition at line 12 of file k09msgq.ino.
Referenced by setup().
pTask2
struct k_t * pTask2
Definition at line 12 of file k09msgq.ino.
Referenced by setup().
t2Hit
volatile int t2Hit = 0
Definition at line 20 of file k09msgq.ino.
t2Missed
volatile int t2Missed = 0
Definition at line 20 of file k09msgq.ino.
timedSem1
struct k_t* timedSem1
Definition at line 18 of file k09msgq.ino.
Referenced by setup(), and task1().
timedSem2
struct k_t * timedSem2
Definition at line 18 of file k09msgq.ino.
Referenced by setup(), and task2().