krnl: examples/oldobsolete/old/k0skeleton/k0skeleton.ino File Reference
k0skeleton.ino File Reference
#include <krnl.h>
Functions
void t1 (void)
void t2 (void)
void setup ()
void loop ()
Variables
struct k_t * pt1
struct k_t * pt2
char s1 [200]
char s2 [200]
Function Documentation
loop()
void loop ()
Definition at line 68 of file k0skeleton.ino.
setup()
void setup ()
Definition at line 36 of file k0skeleton.ino.
References k_crt_task(), k_init(), k_start(), pt1, pt2, s1, s2, t1(), and t2().
t1()
void t1 (void)
Definition at line 13 of file k0skeleton.ino.
References k_sleep().
Referenced by setup().
t2()
void t2 (void)
Definition at line 24 of file k0skeleton.ino.
References k_sleep().
Referenced by setup().
Variable Documentation
pt1
struct k_t* pt1
Definition at line 7 of file k0skeleton.ino.
Referenced by setup().
pt2
struct k_t * pt2
Definition at line 8 of file k0skeleton.ino.
Referenced by setup().
s1
char s1[200]
Definition at line 10 of file k0skeleton.ino.
Referenced by setup().
s2
char s2[200]
Definition at line 11 of file k0skeleton.ino.
Referenced by setup().