dit projekt: krnl.h File Reference
krnl.h File Reference
Data Structures
struct k_t
struct k_msg_t
struct k_rwlock_t
Macros
#define KRNL_VRS 20221027
#define KRNLBUG
#define BACKSTOPPER
#define READERWRITER
#define WDT_PERIOD WDTO_1S
#define DYNMEMORY
#define sbi(r, b) r |= _BV(b)
#define cbi(r, b) r &= ~_BV(b)
#define cbi(r, b) r &= ~_BV(b)
#define QHD_PRIO 102
#define ZOMBI_PRIO (QHD_PRIO - 1)
#define DMY_PRIO (QHD_PRIO - 2)
#define DMY_STK_SZ 90
#define MAIN_PRIO 50
#define STAK_HASH 0x5c
#define MAX_SEM_VAL 50
#define MAX_INT 0x7FFF
#define SEM_MAX_VALUE 10000
#define CEILINGFAILPRIO -4
#define CEILINGFAILNOTCEIL -3
#define lo8(X) ((unsigned char)((unsigned int)(X)))
#define hi8(X) ((unsigned char)((unsigned int)(X) >> 8))
#define K_CHG_STAK()
#define d8t13
#define kbreakout
Functions
void * k_malloc (int k)
void k_free (void *m)
void __attribute__ ((weak)) k_wdt_enable(int t)
unsigned long ki_millis (void)
unsigned long k_millis (void)
void k_eat_msec (unsigned int eatTime)
void ki_task_shift (void) __attribute__((naked))
int k_sleep (int time)
struct k_t * k_crt_task (void(*pTask)(void), char prio, char *pS, int stkSize)
int k_set_prio (char prio)
struct k_t * k_crt_sem (int init_val, int maxvalue)
struct k_t * k_crt_mut (int ceiling_prio, int init_val, int maxvalue)
int k_mut_ceil_set (struct k_t *sem, char prio)
int k_mut_ceil_enter (struct k_t *sem, int timeout)
int k_mut_ceil_leave (struct k_t *sem)
int k_mut_ceil (struct k_t *sem, int timeout, void(*fct)(void))
int k_set_sem_timer (struct k_t *sem, int val)
int ki_signal (struct k_t *sem)
int k_signal (struct k_t *sem)
int k_wait (struct k_t *sem, int timeout)
int k_wait2 (struct k_t *sem, int timeout, int *nrClip)
int k_sem_signals_lost (struct k_t *sem)
int ki_wait (struct k_t *sem, int timeout)
int ki_semval (struct k_t *sem)
int k_semval (struct k_t *sem)
int k_clear_sem (struct k_t *sem)
int ki_msg_count (struct k_msg_t *msgbuffer)
int k_msg_count (struct k_msg_t *m)
struct k_msg_t * k_crt_send_Q (int nr_el, int el_size, void *pBuf)
char ki_send (struct k_msg_t *pB, void *el)
char k_send (struct k_msg_t *pB, void *el)
char k_receive (struct k_msg_t *pB, void *el, int timeout, int *lost_msg)
char ki_receive (struct k_msg_t *pB, void *el, int *lost_msg)
int ki_clear_msg_Q (struct k_msg_t *pB)
int k_clear_msg_Q (struct k_msg_t *pB)
void k_rwInit (struct k_rwlock_t *lock)
int k_rwRdEnter (struct k_rwlock_t *lock, int timeout)
int k_rwWrEnter (struct k_rwlock_t *lock, int timeout)
int k_rwRdLeave (struct k_rwlock_t *lock)
int k_rwWrLeave (struct k_rwlock_t *lock)
int k_tmrInfo (void)
int k_init (int nrTask, int nrSem, int nrMsg)
int k_start (void)
int k_stop ()
void k_reset ()
int k_stk_chk (struct k_t *t)
int k_unused_stak (struct k_t *t)
void k_round_robbin (void)
void k_release (void)
int freeRam (void)
Variables
int k_task
int k_sem
int k_msg
volatile char krnl_preempt_flag
char dmy_stk [DMY_STK_SZ]
volatile char k_wdt_enabled
struct k_t * task_pool
struct k_t * sem_pool
struct k_t AQ
struct k_t * pmain_el
struct k_t * pAQ
struct k_t * pDmy
struct k_t * pRun
struct k_t * pSleepSem
struct k_msg_t * send_pool
char nr_task
char nr_sem
char nr_send
volatile char k_running
volatile char k_err_cnt
unsigned long k_millis_counter
char k_preempt_flag
volatile char k_bug_on
void int nrClip
void int val
Macro Definition Documentation
BACKSTOPPER
#define BACKSTOPPER
Definition at line 75 of file krnl.h.
cbi [1/2]
#define cbi (r, b) r &= ~_BV(b)
Definition at line 261 of file krnl.h.
cbi [2/2]
#define cbi (r, b) r &= ~_BV(b)
Definition at line 261 of file krnl.h.
CEILINGFAILNOTCEIL
#define CEILINGFAILNOTCEIL -3
Definition at line 278 of file krnl.h.
CEILINGFAILPRIO
#define CEILINGFAILPRIO -4
Definition at line 277 of file krnl.h.
d8t13
#define d8t13
Value:
  for (int i = 8; i < 14; i++) {                                               \
    pinMode(i, OUTPUT);                                                        \
    digitalWrite(i, LOW);                                                      \
  }
Definition at line 785 of file krnl.h.
DMY_PRIO
#define DMY_PRIO (QHD_PRIO - 2)
Definition at line 268 of file krnl.h.
DMY_STK_SZ
#define DMY_STK_SZ 90
Definition at line 269 of file krnl.h.
DYNMEMORY
#define DYNMEMORY
Definition at line 90 of file krnl.h.
hi8
#define hi8 (X) ((unsigned char)((unsigned int)(X) >> 8))
Definition at line 482 of file krnl.h.
K_CHG_STAK
#define K_CHG_STAK ()
Value:
  if (pRun != AQ.next) {                                                       \
    pRun->sp_lo = SPL;                                                         \
    pRun->sp_hi = SPH;                                                         \
    pRun = AQ.next;                                                            \
    k_breakout();                                                              \
    SPL = pRun->sp_lo;                                                         \
    SPH = pRun->sp_hi;                                                         \
  }
Definition at line 487 of file krnl.h.
kbreakout
#define kbreakout
Value:
  extern "C" {                                                                 \
  void k_breakout() { PORTB = (1 << pRun->nr); }                               \
  }
Definition at line 791 of file krnl.h.
KRNL_VRS
#define KRNL_VRS 20221027
Definition at line 62 of file krnl.h.
KRNLBUG
#define KRNLBUG
Definition at line 70 of file krnl.h.
lo8
#define lo8 (X) ((unsigned char)((unsigned int)(X)))
Definition at line 481 of file krnl.h.
MAIN_PRIO
#define MAIN_PRIO 50
Definition at line 270 of file krnl.h.
MAX_INT
#define MAX_INT 0x7FFF
Definition at line 273 of file krnl.h.
MAX_SEM_VAL
#define MAX_SEM_VAL 50
Definition at line 272 of file krnl.h.
QHD_PRIO
#define QHD_PRIO 102
Definition at line 266 of file krnl.h.
READERWRITER
#define READERWRITER
Definition at line 78 of file krnl.h.
sbi
#define sbi (r, b) r |= _BV(b)
Definition at line 253 of file krnl.h.
SEM_MAX_VALUE
#define SEM_MAX_VALUE 10000
Definition at line 275 of file krnl.h.
STAK_HASH
#define STAK_HASH 0x5c
Definition at line 271 of file krnl.h.
WDT_PERIOD
#define WDT_PERIOD WDTO_1S
Definition at line 84 of file krnl.h.
ZOMBI_PRIO
#define ZOMBI_PRIO (QHD_PRIO - 1)
Definition at line 267 of file krnl.h.
Function Documentation
__attribute__()
void __attribute__ ((weak))
Call wdt_enable (AVR lib) DI(); wdt_enable(WDT_PERIOD); EI(); WDT_PERIOD is in KRNL i sec
Parameters
[t] watchdog timout WDT_PERIOD is 1 sec See avrlib docu for more info The watchdog is reset in krnls timer ISR when active
disable wdt Disable the watchdog timer
a function for overloading on usersite which is called when a semaphore is overflooding no occur - it's only reading out semaphore idendity Signal operations has not taken place ! 1: means first semahore allocated by user, 2 the next etc Interrupt is disabled when called and must not be enabled during.. so no print etc
Parameters
[in] nr id of semaphore 1,2,3,...
[in] nrClip number of times clip has occured (may be reset by call k_wait_lost)
called in a signal call val is sem val AFTER signal has taken place
Parameters
[out] nr number of semaphore. Semaphores are allocated by user buth also in message queues. So it may be diff to find the semaphore...
called when wait called. val is sem value after countdown has taken place NB is the wait call willl not wait and there is no token at the semaphore val will be -1111
a function for overloading on usersite which is called when a msgQ is overflooding no reset occur - it's only readind out smsgQ idendity 1: means first msgQ allocated by user etc Interrupt is disabled when called and must not be enabled during.. so no print etc
Parameters
[out] nr : id of send Q 0,1,2,...
[out] nrClip number of times clip has occured (may be reset by call k_receive and lost parm not eq NULL)
Breakout function called from scheduler You can use to examine who is runnning and who is next NB NB should be fast code and remember interrupt is and must be disables pRun->nr Nr of running. dummy has nr == 0 then task is numbered 1.. in acc with order of creation of tasks k_breakout is defined as weak function so you can write your own k_breakout The builtin k_breakout has no code and just a placeholder to be subst with your code. setting led8-12 on uno as task number PORTB = (1 << pRun->nr) | led13
freeRam()
int freeRam (void)
returns amount of free memory in your system (free size of heap) se docu in krnl.c
Definition at line 521 of file krnl.c.
References x.
k_clear_msg_Q()
int k_clear_msg_Q (struct k_msg_t * pB)
Empty sendQ See ki_clear_msg-Q for description
Definition at line 972 of file krnl.c.
References ki_clear_msg_Q(), and k_msg_t::r.
k_clear_sem()
int k_clear_sem (struct k_t * sem)
Clear semaphore if possible. Will set semaphore vallue 0 if possible (if no tasks is waiting)
Parameters
[in] sem pointer ref to semaphore
Returns
semValue - if negative it indicates task are waiting
Definition at line 765 of file krnl.c.
References k_t::clip, and k_t::cnt1.
k_crt_mut()
struct k_t* k_crt_mut (int ceiling_prio, int init_val, int maxvalue)
adds ceiling priority to semaphore use k_mut_ceil_enter k_mut_ceil_leave instead of wait and signal Can only be called before k_start
Parameters
[in] sem reference to sem used for mutex - no check
[in] prio Ceiling pirority
Returns
0: ok , otherwise bad bad
Remarks
only to be called before start of KRNL creates a standard mutex. It can be initialized to values in range [0..maxvalue]
Parameters
[in] init_val startvalue of semaphore 0,1,2,... maxvalue
[in] maxvalue which is maxvalue semaphore can reach
Returns
handle to semaphore or NULL pointer
Remarks
only to be called before start of KRNL
Definition at line 789 of file krnl.c.
References k_t::ceiling_prio, k_crt_sem(), k_err_cnt, and k_running.
k_crt_sem()
struct k_t* k_crt_sem (int init_val, int maxvalue)
creates a standard Dijkstra semaphore. It can be initialized to values in range [0..maxvalue]
Parameters
[in] init_val startvalue of semaphore 0,1,2,... maxvalue
[in] maxvalue which is maxvalue semaphore can reach
Returns
handle to semaphore or NULL pointer
Remarks
only to be called before start of KRNL
Definition at line 620 of file krnl.c.
References k_t::ceiling_prio, k_t::clip, k_t::cnt1, k_t::cnt2, k_err_cnt, k_running, k_sem, k_t::maxv, k_t::next, k_t::nr, nr_sem, k_t::pred, k_t::prio, QHD_PRIO, k_t::saved_prio, SEM_MAX_VALUE, and sem_pool.
Referenced by k_crt_mut(), k_crt_send_Q(), k_init(), k_rwInit(), and setup().
k_crt_send_Q()
struct k_msg_t* k_crt_send_Q (int nr_el, int el_size, void * pBuf)
Definition at line 914 of file krnl.c.
References k_msg_t::cnt, k_msg_t::el_size, k_crt_sem(), k_err_cnt, k_msg, k_running, k_sem, k_msg_t::lost_msg, k_msg_t::nr, k_msg_t::nr_el, nr_sem, nr_send, k_msg_t::pBuf, k_msg_t::r, k_msg_t::sem, send_pool, and k_msg_t::w.
Referenced by setup().
k_crt_task()
struct k_t* k_crt_task (void(*)(void) pTask, char prio, char * pS, int stkSize)
creates a task and put it in the active Q
Parameters
[in] pTask pointer to function for code (void task(void) ...)
[in] stkSize size of data area(in bytes) to be used for stak
[in] prio - task prio max: 1 lowest < DUMMY_PRIO
Returns
: pointer to task handle or NULL if no success
Remarks
only to be called before start of KRNL but after k_init
Definition at line 433 of file krnl.c.
References k_t::cnt1, k_t::cnt2, k_t::cnt3, DMY_PRIO, hi8, i, jumper(), k_err_cnt, k_running, k_task, lo8, k_t::maxv, k_t::nr, nr_task, pAQ, k_t::prio, prio_enQ(), k_t::pt, pTask, k_t::sp_hi, k_t::sp_lo, STAK_HASH, and task_pool.
Referenced by setup().
k_eat_msec()
void k_eat_msec (unsigned int eatTime)
Eat time in quant of krnl ticks starting from now but not from next tick Eats CPU time in k_tick quants
Parameters
[in] tyick number of ticks to eat
Definition at line 297 of file krnl.c.
Referenced by getDataInCritRegion(), t1(), t2(), task(), task1(), task2(), tgeneric(), tnoise(), and tperiodic().
k_free()
void k_free (void * m)
call free empty - no function if dft as weak so you can supply with your own
Remarks
do no free mem bq we do not want fragmented memory
k_init()
int k_init (int nrTask, int nrSem, int nrMsg)
Initialise KRNL. First function to be called. You have to give max number of tasks, semaphores and message queues you will use
Parameters
[in] nrTask ...
[in] nrSem ...
[in] nrMsg ...
Definition at line 1178 of file krnl.c.
References AQ, k_t::cnt2, k_t::cnt3, DMY_PRIO, k_crt_sem(), k_err_cnt, k_msg, k_running, k_sem, k_task, k_t::next, k_t::nr, nr_send, nr_task, pAQ, pmain_el, k_t::pred, k_t::prio, prio_enQ(), pSleepSem, QHD_PRIO, sem_pool, send_pool, and task_pool.
Referenced by setup().
k_malloc()
void* k_malloc (int k)
call malloc protected by DI and EI if dft as weak so you can supply with your own
k_millis()
unsigned long k_millis (void)
Returns nr of milliseconds since krnl was started by k_start
Returns
: unsigned long is returned
Remarks
only to be called after start of KRNL
Interrupt is disabled when reading krnl time and is enabled afterwards
Definition at line 1336 of file krnl.c.
References k_millis_counter.
Referenced by t2().
k_msg_count()
int k_msg_count (struct k_msg_t * m)
returns nr of pending messages
Parameters
[in] msgbuffer handle
Returns
1: ok not suspended, 0: ok you have been suspended
-1 no wait maybe bq no timeout was allowed
Remarks
only to be called after start of KRNL
Definition at line 906 of file krnl.c.
References ki_msg_count().
k_mut_ceil()
int k_mut_ceil (struct k_t * sem, int timeout, void(*)(void) fct)
Mutex enter and leave w imm priority ceiling in one operation
Parameters
sm mutex with ceiling
timeout 0 == forever @fct void fct(void) the function w critical code
Returns
0: ok ,waited, 1 straight through; -1 timeout, -3 CEILINGFAILNOTCEIL not a semaphore w ceiling, -4 CEILINGFAIL my priority is above ceil max prio
Definition at line 812 of file krnl.c.
References k_mut_ceil_enter(), and k_mut_ceil_leave().
k_mut_ceil_enter()
int k_mut_ceil_enter (struct k_t * sem, int timeout)
Enter mutex (eq to k_wait...) use k_mut_enter / k_mut_leave instead of wait and signal
Parameters
[in] sem aka mutex
[in] timeout timeout value
Returns
0: if you have been waiting, 1 if you just went through, -1 for timeout, -3 if your priority was higher than ceiling priority
Definition at line 825 of file krnl.c.
References k_t::ceiling_prio, CEILINGFAILNOTCEIL, CEILINGFAILPRIO, deQ(), ki_task_shift(), ki_wait(), pAQ, k_t::prio, prio_enQ(), pRun, and k_t::saved_prio.
Referenced by k_mut_ceil().
k_mut_ceil_leave()
int k_mut_ceil_leave (struct k_t * sem)
Leave mutex (eq to k_signal...) use k_mut_enter/ k_mut_leave instead of wait and signal
Parameters
[in] sem used as mutex
Returns
0: ok otherwise bad bad
Definition at line 858 of file krnl.c.
References deQ(), ki_signal(), ki_task_shift(), pAQ, k_t::prio, prio_enQ(), pRun, and k_t::saved_prio.
Referenced by k_mut_ceil().
k_mut_ceil_set()
int k_mut_ceil_set (struct k_t * sem, char prio)
Definition at line 605 of file krnl.c.
References k_t::ceiling_prio, DMY_PRIO, k_running, and k_t::prio.
k_receive()
char k_receive (struct k_msg_t * pB, void * el, int timeout, int * lost_msg)
Receive data (one element of el_size)in the ringbuffer if there are data DONE BY COPY !
Parameters
[in] pB Ref to message buffer
[out] el Reference to where data shall be copied to at your site
[in] timeout Max time you want to wait on data, -1: never, 0: forever, positive: nr of KRNL timer quants
[out] lost_msg nr of lost messages since last receive. will clip at
If lost_msg ptr is NULL then overrun counter is not reset to 0.
Returns
1: ok no suspension, 0: operation did succed, -1: no data in ringbuffer
Remarks
only to be called after start of KRNL
Definition at line 1064 of file krnl.c.
References k_msg_t::cnt, k_msg_t::el_size, i, ki_wait(), k_msg_t::lost_msg, k_msg_t::nr_el, k_msg_t::pBuf, k_msg_t::r, and k_msg_t::sem.
Referenced by task2().
k_release()
void k_release (void)
release switch running to task in front of Active Q calls ki_task_shift (); enveloped by a DI and EI no round robbin
Definition at line 1155 of file krnl.c.
References ki_task_shift().
k_reset()
void k_reset ()
Reset by disable interrupt plus activate watchdog (15 millisseconds) and just wait...
k_round_robbin()
void k_round_robbin (void)
round robbin reinsert running task in activeQ. so running will be inserted after other tasks with same or higher priority
Definition at line 1144 of file krnl.c.
References deQ(), ki_task_shift(), pAQ, prio_enQ(), and pRun.
k_rwInit()
void k_rwInit (struct k_rwlock_t * lock)
initialise a reader-writers comples
Definition at line 1106 of file krnl.c.
References k_rwlock_t::fifoSem, k_crt_sem(), k_rwlock_t::nrReaders, k_rwlock_t::rdSem, and k_rwlock_t::rdwrSem.
k_rwRdEnter()
int k_rwRdEnter (struct k_rwlock_t * lock, int timeout)
reader-writer Read enter
Definition at line 1113 of file krnl.c.
References k_rwlock_t::fifoSem, k_signal(), k_wait(), k_rwlock_t::nrReaders, k_rwlock_t::rdSem, and k_rwlock_t::rdwrSem.
k_rwRdLeave()
int k_rwRdLeave (struct k_rwlock_t * lock)
reader-writer Read leave
Definition at line 1131 of file krnl.c.
References k_signal(), k_wait(), k_rwlock_t::nrReaders, k_rwlock_t::rdSem, and k_rwlock_t::rdwrSem.
k_rwWrEnter()
int k_rwWrEnter (struct k_rwlock_t * lock, int timeout)
reader-writer Write enter
Definition at line 1125 of file krnl.c.
References k_rwlock_t::fifoSem, k_signal(), k_wait(), and k_rwlock_t::rdwrSem.
k_rwWrLeave()
int k_rwWrLeave (struct k_rwlock_t * lock)
reader-writer Write leave
Definition at line 1140 of file krnl.c.
References k_signal(), and k_rwlock_t::rdwrSem.
k_sem_signals_lost()
int k_sem_signals_lost (struct k_t * sem)
Returns how many signals has been lost on semaphore due to saturation
Parameters
[in] sem semaphore handle
Returns
nr of signals lost
Remarks
only to be called after start of KRNL
Definition at line 876 of file krnl.c.
References k_t::clip, and x.
k_semval()
int k_semval (struct k_t * sem)
returns value of semaphore
Parameters
[in] sem semaphore handle
Returns
1: ok not suspended, 0: ok you have been suspended
-1 no wait maybe bq no timeout was allowed
Remarks
only to be called after start of KRNL
Definition at line 894 of file krnl.c.
References ki_semval().
k_send()
char k_send (struct k_msg_t * pB, void * el)
Put data (one element of el_size)in the ringbuffer if there are room for it. DONE BY COPY !
Parameters
[in] pB Ref to message buffer
[in] el Reference to data to be put in buffer. Size if already given in k_crt_send
Returns
0: operation did succed, -1: no room in ringbuffer
Remarks
only to be called after start of KRNL
k_send does not block if no space in buffer. Instead -1 is returned
Definition at line 1017 of file krnl.c.
References ki_send(), and ki_task_shift().
Referenced by task1().
k_set_prio()
int k_set_prio (char prio)
change priority of calling task)
Parameters
[in] prio new prio, Priority 1: highest (QHEAD_PRIO-1): lowest
Returns
: 0: ok, -1: KRNL not running, -2: illegal value
Remarks
only to be called after start of KRNL
Definition at line 579 of file krnl.c.
References deQ(), DMY_PRIO, i, k_running, ki_task_shift(), pAQ, k_t::prio, prio_enQ(), and pRun.
k_set_sem_timer()
int k_set_sem_timer (struct k_t * sem, int val)
attach a timer to the semaphore so KRNL will signal the semaphore with regular intervals. Can be used for cyclic real time run of a task.
Parameters
[in] sem semaphore handle
[in] val interval in quant of KRNL ticks (0: disable cyclic timer, 1,2,3... cyclic quant)
Returns
-1: negative val, 0. ok
Remarks
only to be called after start of KRNL
Definition at line 660 of file krnl.c.
References k_t::cnt1, k_t::cnt2, k_t::cnt3, and val.
Referenced by t1(), task(), task1(), task2(), and tperiodic().
k_signal()
int k_signal (struct k_t * sem)
Signal a semaphore. Task shift will task place if a task is started by the signal and has higher priority than you.
Parameters
[in] sem semaphore handle
Returns
0: ok , -1: max value of semaphore reached
Remarks
The ki_ indicates that interrups is NOT enabled when leaving ki_signal
only to be called after start of KRNL
Definition at line 710 of file krnl.c.
References ki_signal(), and ki_task_shift().
Referenced by getDataInCritRegion(), k_rwRdEnter(), k_rwRdLeave(), k_rwWrEnter(), k_rwWrLeave(), saveDataInCritRegion(), saveDataInCritRegionNoWait(), task(), task1(), and task2().
k_sleep()
int k_sleep (int time)
Set task asleep for a number of ticks.
Parameters
[in] time nr of ticks to sleep < 0
Returns
: 0 is ok(has been suspended), 1(is not suspended), -1 is wait time is less than 0
Remarks
only to be called after start of KRNL
Definition at line 547 of file krnl.c.
References k_wait(), and pSleepSem.
Referenced by t1(), t2(), task(), task2(), tgeneric(), and tnoise().
k_start()
int k_start (void)
Starts krnl is possible If there has been ciritcal errors between k_init and k_start (like no more task descriptors) k_start will return a negative number indicatin how many errors
If k_start starts you will not return from k_start
Definition at line 1217 of file krnl.c.
References k_err_cnt, k_running, k_tick_size, ki_task_shift(), pmain_el, pRun, and tcntValue.
Referenced by setup().
k_stk_chk()
int k_stk_chk (struct k_t * t)
Initialise blink on pin 13 ON when dummy is running Nov 2014 - fake do not use it bq it will not work for emergency use :-) returns nr of unbytes bytes on stak. For chekking if stak is too big or to small...
Parameters
[in] t Reference to task (by task handle) If null then yourself
Returns
: nr of unused bytes on stak (int)
Remarks
only to be called after start of KRNL
no chk of if it is a valid task
k_stop()
int k_stop ()
stop KRNL If krnl is not yet running you will return with a -1 as return value If krnl is running interrupt will be disabled and k_stop ends in an infinite loop
Definition at line 1310 of file krnl.c.
References k_running.
k_tmrInfo()
int k_tmrInfo (void)
returns which timer is used
Returns
0,1,2,3,4,5 ...
Definition at line 1345 of file krnl.c.
k_unused_stak()
int k_unused_stak (struct k_t * t)
Returns amount of unused stak
Parameters
[in] t Ptr to taskdescriptor. If NULL it is yourself
Returns
: amount of unused stak(in bytes)
Remarks
: a watermark philosophy is used
Definition at line 556 of file krnl.c.
References k_t::cnt1, i, pRun, and STAK_HASH.
k_wait()
int k_wait (struct k_t * sem, int timeout)
Wait on a semaphore. Task shift will task place if you are blocked.
Parameters
[in] sem semaphore handle
[in] timeout "<0" you will be started after timeout ticks, "=0" wait forever "-1" you will not wait
Returns
1: ok there was a signal hanging - so no suspension
0: ok- you have been suspended
-1: timeout has occured, -2 no wait bq timeout was -1 and semaphore was negative
Remarks
only to be called after start of KRNL
Definition at line 757 of file krnl.c.
References ki_wait().
Referenced by getDataInCritRegion(), k_rwRdEnter(), k_rwRdLeave(), k_rwWrEnter(), k_sleep(), saveDataInCritRegion(), saveDataInCritRegionNoWait(), t1(), task(), task1(), task2(), and tperiodic().
k_wait2()
int k_wait2 (struct k_t * sem, int timeout, int * nrClip)
Wait on a semaphore. Task shift will task place if you are blocked.
Parameters
[in] sem semaphore handle
[in] timeout "<0" you will be started after timeout ticks, "=0" wait forever "-1" you will not wait
[out] nrClip If not NULL you will get in return nr of clip on signals on sem and clip counter will be set to 0
Returns
1: ok there was a signal hanging - so no suspension
0: ok- you have been suspended
-1: timeout has occured, -2 no wait bq timeout was -1 and semaphore was negative
Remarks
only to be called after start of KRNL
Definition at line 777 of file krnl.c.
References k_t::clip, ki_wait(), and nrClip.
Referenced by task1().
ki_clear_msg_Q()
int ki_clear_msg_Q (struct k_msg_t * pB)
Empty sendQ
Returns
given no of deleted messages
-1 if its no a msg q
-2 if krnl is not running
0 or positive gives no of messages deleted
Definition at line 954 of file krnl.c.
References k_msg_t::cnt, k_t::cnt1, k_running, k_msg_t::lost_msg, k_msg_t::r, k_msg_t::sem, and k_msg_t::w.
Referenced by k_clear_msg_Q().
ki_millis()
unsigned long ki_millis (void)
Returns nr of milliseconds since krnl was started by k_start
Returns
: unsigned long is returned
Remarks
only to be called after start of KRNL and only when interrupt is disabled
To be called within an ISR so interrupts is no disabled
Definition at line 1329 of file krnl.c.
References k_millis_counter.
ki_msg_count()
int ki_msg_count (struct k_msg_t * msgbuffer)
returns nr of pending messages
Parameters
[in] msgbuffer handle xxx
Definition at line 901 of file krnl.c.
References k_msg_t::cnt.
Referenced by k_msg_count().
ki_receive()
char ki_receive (struct k_msg_t * pB, void * el, int * lost_msg)
Receive data (one element of el_size)in the ringbuffer if there are data DONE BY COPY ! No blocking if no data Interrupt will not be enabled after ki_receive and intr must be blocked prior to call
Parameters
[in] pB Ref to message buffer
[out] el Reference to where data shall be copied to at your site
[out] lost_msg nr of lost messages since last receive. will clip at
If lost_msg ptr is NULL then overrun counter is not reset to 0
Returns
1: data was rdy no suspension, 0: ok you have been suspended , -1: no data in ringbuffer
Remarks
can be used from ISR
only to be called after start of KRNL
Definition at line 1032 of file krnl.c.
References k_msg_t::cnt, k_msg_t::el_size, i, ki_wait(), k_msg_t::lost_msg, k_msg_t::nr_el, k_msg_t::pBuf, k_msg_t::r, and k_msg_t::sem.
ki_semval()
int ki_semval (struct k_t * sem)
returns value of semaphore
Parameters
[in] sem semaphore handle
Returns
1: ok not suspended, 0: ok you have been suspended
-1 no wait maybe bq no timeout was allowed
Remarks
only to be called after start of KRNL
do not enable interrupt upon leaving
Definition at line 888 of file krnl.c.
References k_t::cnt1.
Referenced by k_semval().
ki_send()
char ki_send (struct k_msg_t * pB, void * el)
Put data (one element of el_size)in the ringbuffer if there are room for it. Intended for ISR use DONE BY COPY !
Parameters
[in] pB Ref to message buffer
[in] el Reference to data to be put in buffer. Size if already given in k_crt_send
Returns
0: operation did succed, -1: no room in ringbuffer
Remarks
Interrupt will not enabled upon leaving, so ki_send is intended to be used from an ISR
only to be called before start of KRNL
Definition at line 980 of file krnl.c.
References k_msg_t::cnt, k_msg_t::el_size, i, ki_signal(), k_msg_t::lost_msg, k_msg_t::nr, k_msg_t::nr_el, k_msg_t::pBuf, k_msg_t::sem, SEM_MAX_VALUE, and k_msg_t::w.
Referenced by k_send().
ki_signal()
int ki_signal (struct k_t * sem)
Signal a semaphore. Can be called from an ISR when interrupt is disabled. No task shift will occur - only queue manipulation.
Parameters
[in] sem semaphore handle
Returns
0: ok , -1: max value of semaphore reached
Remarks
only to be called after start of KRNL
Definition at line 679 of file krnl.c.
References k_t::clip, k_t::cnt1, k_t::cnt2, deQ(), k_sem_clip(), MAX_SEM_VAL, k_t::maxv, k_t::next, k_t::nr, pAQ, and prio_enQ().
Referenced by ISR(), k_mut_ceil_leave(), k_signal(), and ki_send().
ki_task_shift()
void ki_task_shift (void)
issues a task shift - handle with care Not to be used by normal user
Referenced by k_mut_ceil_enter(), k_mut_ceil_leave(), k_release(), k_round_robbin(), k_send(), k_set_prio(), k_signal(), k_start(), and ki_wait().
ki_wait()
int ki_wait (struct k_t * sem, int timeout)
Like k_wait with the exception interrupt is NOT enabled when leaving
Parameters
[in] sem semaphore handle
[in] timeout "<0" you will be started after timeout ticks, "=0" wait forever "-1" you will not wait
Returns
0: ok , -1: could do wait bw blocking would have taken place
Remarks
The ki_ indicates that interrups is NOT enabled when leaving ki_wait
only to be called after start of KRNL
normally not to be used by users !!! BEWARE
Definition at line 727 of file krnl.c.
References k_t::cnt1, k_t::cnt2, k_t::cnt3, deQ(), enQ(), ki_task_shift(), and pRun.
Referenced by k_mut_ceil_enter(), k_receive(), k_wait(), k_wait2(), and ki_receive().
Variable Documentation
AQ
struct k_t AQ
Definition at line 378 of file krnl.h.
dmy_stk
char dmy_stk[DMY_STK_SZ]
k_bug_on
volatile char k_bug_on
k_err_cnt
volatile char k_err_cnt
Definition at line 226 of file krnl.c.
Referenced by k_crt_mut(), k_crt_sem(), k_crt_send_Q(), k_crt_task(), k_init(), and k_start().
k_millis_counter
unsigned long k_millis_counter
Definition at line 234 of file krnl.c.
Referenced by ISR(), k_millis(), and ki_millis().
k_msg
int k_msg
Definition at line 335 of file krnl.h.
k_preempt_flag
char k_preempt_flag
k_running
volatile char k_running
Definition at line 226 of file krnl.c.
Referenced by ISR(), k_crt_mut(), k_crt_sem(), k_crt_send_Q(), k_crt_task(), k_init(), k_mut_ceil_set(), k_set_prio(), k_start(), k_stop(), and ki_clear_msg_Q().
k_sem
int k_sem
Definition at line 335 of file krnl.h.
k_task
int k_task
Definition at line 223 of file krnl.c.
Referenced by k_crt_task(), and k_init().
k_wdt_enabled
volatile char k_wdt_enabled
Referenced by ISR().
krnl_preempt_flag
volatile char krnl_preempt_flag
nr_sem
char nr_sem
Definition at line 385 of file krnl.h.
nr_send
char nr_send
Definition at line 385 of file krnl.h.
nr_task
char nr_task
Definition at line 224 of file krnl.c.
Referenced by ISR(), k_crt_task(), and k_init().
nrClip
void int nrClip
Definition at line 1111 of file krnl.h.
Referenced by k_wait2().
pAQ
struct k_t * pAQ
Definition at line 379 of file krnl.h.
pDmy
struct k_t * pDmy
Definition at line 379 of file krnl.h.
pmain_el
struct k_t * pmain_el
Definition at line 379 of file krnl.h.
pRun
struct k_t * pRun
Definition at line 380 of file krnl.h.
pSleepSem
struct k_t * pSleepSem
Definition at line 381 of file krnl.h.
sem_pool
struct k_t * sem_pool
Definition at line 378 of file krnl.h.
send_pool
struct k_msg_t* send_pool
Definition at line 221 of file krnl.c.
Referenced by k_crt_send_Q(), and k_init().
task_pool
struct k_t* task_pool
Definition at line 212 of file krnl.c.
Referenced by ISR(), k_crt_task(), and k_init().
val
void int val
Definition at line 1121 of file krnl.h.
Referenced by k_set_sem_timer().