krnl: examples/oldobsolete/old/krnlregistercodetime/krnlregistercodetime.ino File Reference
krnlregistercodetime.ino File Reference
#include <krnl.h>
Data Structures
struct shft
Macros
#define STAKSIZE 100
Functions
void t1 ()
void t2 ()
void setup ()
void loop ()
void k_breakout ()
Variables
struct k_t * pT1
struct k_t * pT2
struct k_t * sem1
struct k_t * sem2
char stak1 [STAKSIZE]
char stak2 [STAKSIZE]
struct shft logg [200]
volatile int wI = 0
unsigned long k_millis_counter
Macro Definition Documentation
STAKSIZE
#define STAKSIZE 100
Definition at line 7 of file krnlregistercodetime.ino.
Function Documentation
k_breakout()
void k_breakout ()
Definition at line 78 of file krnlregistercodetime.ino.
References k_millis_counter, logg, k_t::nr, shft::nrr, pRun, shft::t, and wI.
loop()
void loop ()
Definition at line 69 of file krnlregistercodetime.ino.
setup()
void setup ()
Definition at line 55 of file krnlregistercodetime.ino.
References k_crt_sem(), k_crt_task(), k_init(), k_start(), pT1, pT2, sem1, sem2, stak1, stak2, STAKSIZE, t1(), and t2().
t1()
void t1 ()
eat time acc to code time
Definition at line 20 of file krnlregistercodetime.ino.
References i, k_set_sem_timer(), k_wait(), logg, shft::nrr, sem1, t, and wI.
Referenced by setup().
t2()
void t2 ()
Definition at line 43 of file krnlregistercodetime.ino.
References k_set_sem_timer(), k_wait(), and sem2.
Referenced by setup().
Variable Documentation
k_millis_counter
unsigned long k_millis_counter
Definition at line 217 of file krnl.c.
Referenced by k_breakout(), and wr().
logg
struct shft logg[200]
Definition at line 16 of file krnlregistercodetime.ino.
Referenced by k_breakout(), and t1().
pT1
struct k_t* pT1
Definition at line 3 of file krnlregistercodetime.ino.
Referenced by setup().
pT2
struct k_t * pT2
Definition at line 3 of file krnlregistercodetime.ino.
Referenced by setup().
sem1
struct k_t* sem1
Definition at line 5 of file krnlregistercodetime.ino.
Referenced by setup(), and t1().
sem2
struct k_t * sem2
Definition at line 5 of file krnlregistercodetime.ino.
Referenced by setup(), and t2().
stak1
char stak1[STAKSIZE]
Definition at line 8 of file krnlregistercodetime.ino.
Referenced by setup().
stak2
char stak2[STAKSIZE]
Definition at line 9 of file krnlregistercodetime.ino.
Referenced by setup().
wI
volatile int wI = 0
Definition at line 17 of file krnlregistercodetime.ino.
Referenced by k_breakout(), and t1().