krnl: examples/oldobsolete/old/krnldebug01/krnldebug01.ino File Reference
krnldebug01.ino File Reference
#include <krnl.h>
Functions
void t1 ()
void setup ()
void loop ()
void k_breakout ()
Variables
struct k_t * p
char stak [100]
volatile int cntt1 = 0
volatile int cntt2 = 0
Function Documentation
k_breakout()
void k_breakout ()
Definition at line 45 of file krnldebug01.ino.
References cntt1, cntt2, k_t::nr, and pRun.
loop()
void loop ()
Definition at line 37 of file krnldebug01.ino.
setup()
void setup ()
Definition at line 24 of file krnldebug01.ino.
References k_crt_task(), k_init(), k_start(), p, stak, and t1().
t1()
void t1 ()
Definition at line 9 of file krnldebug01.ino.
References cntt1, cntt2, k_eat_msec_time, and k_sleep().
Referenced by setup().
Variable Documentation
cntt1
volatile int cntt1 = 0
Definition at line 8 of file krnldebug01.ino.
Referenced by k_breakout(), and t1().
cntt2
volatile int cntt2 = 0
Definition at line 8 of file krnldebug01.ino.
Referenced by k_breakout(), and t1().
p
struct k_t* p
Definition at line 6 of file krnldebug01.ino.
Referenced by setup().
stak
char stak[100]
Definition at line 7 of file krnldebug01.ino.
Referenced by setup().