krnl: examples/oldobsolete/old/krnltaskshifttime/krnltaskshifttime.ino File Reference
krnltaskshifttime.ino File Reference
#include <krnl.h>
Macros
#define STK_SIZE 200
Functions
void t2 ()
void t1 (void)
void setup ()
void loop (void)
Variables
struct k_t * p_t1
struct k_t * p_t2
struct k_t * sem1
char s1 [STK_SIZE]
char s2 [STK_SIZE]
volatile int icnt = 0
volatile int i = 0
Macro Definition Documentation
STK_SIZE
#define STK_SIZE 200
Definition at line 17 of file krnltaskshifttime.ino.
Function Documentation
loop()
void loop (void)
Definition at line 89 of file krnltaskshifttime.ino.
setup()
void setup ()
Definition at line 65 of file krnltaskshifttime.ino.
References k_crt_sem(), k_crt_task(), k_init(), k_millis(), k_start(), p_t1, p_t2, s1, s2, sem1, STK_SIZE, t, t1(), and t2().
t1()
void t1 (void)
Definition at line 43 of file krnltaskshifttime.ino.
References i, k_stop(), k_wait(), and sem1.
Referenced by setup().
t2()
void t2 ()
Definition at line 26 of file krnltaskshifttime.ino.
References k_signal(), and sem1.
Referenced by setup().
Variable Documentation
i
volatile int i = 0
Definition at line 41 of file krnltaskshifttime.ino.
Referenced by init_IO_for_debug(), initLED(), k_crt_task(), k_receive(), k_set_prio(), k_unused_stak(), ki_receive(), ki_send(), loop(), setup(), t1(), t2(), task1(), task2(), and wr().
icnt
volatile int icnt = 0
Definition at line 22 of file krnltaskshifttime.ino.
p_t1
struct k_t* p_t1
Definition at line 15 of file krnltaskshifttime.ino.
Referenced by setup().
p_t2
struct k_t * p_t2
Definition at line 15 of file krnltaskshifttime.ino.
Referenced by setup().
s1
char s1[STK_SIZE]
Definition at line 19 of file krnltaskshifttime.ino.
Referenced by setup().
s2
char s2[STK_SIZE]
Definition at line 20 of file krnltaskshifttime.ino.
Referenced by setup().
sem1
struct k_t * sem1
Definition at line 15 of file krnltaskshifttime.ino.
Referenced by setup(), t1(), and t2().