krnl: examples/oldobsolete/old/ksimple01/ksimple01.ino File Reference
ksimple01.ino File Reference
#include <krnl.h>
Macros
#define STK_SIZE 200
Functions
void doBlink (void)
void t1 ()
void setup ()
void loop (void)
Variables
struct k_t * p_t1
char s1 [STK_SIZE]
volatile int icnt =0
Macro Definition Documentation
STK_SIZE
#define STK_SIZE 200
Definition at line 5 of file ksimple01.ino.
Function Documentation
doBlink()
void doBlink (void)
Definition at line 11 of file ksimple01.ino.
Referenced by t1().
loop()
void loop (void)
Definition at line 40 of file ksimple01.ino.
setup()
void setup ()
Definition at line 27 of file ksimple01.ino.
References k_crt_task(), k_init(), k_start(), p_t1, s1, and t1().
t1()
void t1 ()
Definition at line 19 of file ksimple01.ino.
References doBlink(), and k_sleep().
Referenced by setup().
Variable Documentation
icnt
volatile int icnt =0
Definition at line 9 of file ksimple01.ino.
p_t1
struct k_t* p_t1
Definition at line 3 of file ksimple01.ino.
Referenced by setup().
s1
char s1[STK_SIZE]
Definition at line 7 of file ksimple01.ino.
Referenced by setup().