dit projekt: examples/manyinone/manyinone.ino File Reference
manyinone.ino File Reference
#include <krnl.h>
Data Structures
struct shDataTp
Macros
#define STKSIZE 100
#define TASKPRIO 10
#define STKSIZE 100
#define TASKPRIO 10
#define STKSIZE 100
#define TASKPRIO 10
#define STKSIZE 100
#define TASKPRIO 10
#define STKSIZE 100
#define TASKPRIO 10
#define STKSIZE 110
#define TASKPRIO 10
#define STKSIZE 100
#define TASKPRIO 10
#define STKSIZE 100
#define TASKPRIO 10
#define STKSIZE 200
#define TASKPRIO 10
#define STKSIZE 200
#define TASKPRIO 10
#define STK 150
#define STKSZ 200
#define STK 110
#define SS 110
#define STK 110
#define STK 110
#define STK 110
#define STK 150
#define STK 150
#define TASKPRIO 10
#define STK 110
#define STK 110
Functions
void task ()
void task2 ()
void setup ()
void loop ()
void k_sem_clip (unsigned char nr, int i)
void k_sem_unclip (unsigned char nr)
void k_breakout ()
void t1 ()
void t2 (void)
void tperiodic ()
void tnoise ()
void task1 ()
void saveDataInCritRegion (int v)
int saveDataInCritRegionNoWait (int v)
struct shDataTp getDataInCritRegion (void)
void tgeneric ()
Variables
char stak [STKSIZE]
char stak2 [STKSIZE]
struct k_t * pTask
struct k_t * pTask2
unsigned char led13
struct k_t * sem1
volatile char reg = 0
struct k_t * sem2
unsigned char taskStak [STK]
struct k_t * pt1
struct k_t * pt2
unsigned char stak1 [STKSZ]
volatile int i = 0
struct k_t * p1
struct k_t * p2
unsigned char s1 [STK]
unsigned char s2 [STK]
unsigned long tStart
unsigned long tStop
char st1 [STK]
char st2 [STK]
int x = 0
int clipp
int err
int pendingWait = 0
int loopCnt = 0
int er2
char a1 [STK]
char a2 [STK]
struct k_t * semmutex
struct shDataTp sharedData = {0, 0}
volatile int noDataDelivered = 0
struct k_t * pTask1
struct k_msg_t * msgQ
int dataBufForMsgQ [10]
struct k_t * timedSem1
struct k_t * timedSem2
struct k_t * mutSem
volatile int t2Missed = 0
volatile int t2Hit = 0
struct k_t * p3
char st3 [STK]
Macro Definition Documentation
SS
#define SS 110
Definition at line 1507 of file manyinone.ino.
STK [1/9]
#define STK 150
Definition at line 2311 of file manyinone.ino.
STK [2/9]
#define STK 110
Definition at line 2311 of file manyinone.ino.
STK [3/9]
#define STK 110
Definition at line 2311 of file manyinone.ino.
STK [4/9]
#define STK 110
Definition at line 2311 of file manyinone.ino.
STK [5/9]
#define STK 110
Definition at line 2311 of file manyinone.ino.
STK [6/9]
#define STK 150
Definition at line 2311 of file manyinone.ino.
STK [7/9]
#define STK 150
Definition at line 2311 of file manyinone.ino.
STK [8/9]
#define STK 110
Definition at line 2311 of file manyinone.ino.
STK [9/9]
#define STK 110
Definition at line 2311 of file manyinone.ino.
STKSIZE [1/10]
#define STKSIZE 100
Definition at line 1009 of file manyinone.ino.
STKSIZE [2/10]
#define STKSIZE 100
Definition at line 1009 of file manyinone.ino.
STKSIZE [3/10]
#define STKSIZE 100
Definition at line 1009 of file manyinone.ino.
STKSIZE [4/10]
#define STKSIZE 100
Definition at line 1009 of file manyinone.ino.
STKSIZE [5/10]
#define STKSIZE 100
Definition at line 1009 of file manyinone.ino.
STKSIZE [6/10]
#define STKSIZE 110
Definition at line 1009 of file manyinone.ino.
STKSIZE [7/10]
#define STKSIZE 100
Definition at line 1009 of file manyinone.ino.
STKSIZE [8/10]
#define STKSIZE 100
Definition at line 1009 of file manyinone.ino.
STKSIZE [9/10]
#define STKSIZE 200
Definition at line 1009 of file manyinone.ino.
STKSIZE [10/10]
#define STKSIZE 200
Definition at line 1009 of file manyinone.ino.
STKSZ
#define STKSZ 200
Definition at line 1241 of file manyinone.ino.
TASKPRIO [1/11]
#define TASKPRIO 10
Definition at line 2025 of file manyinone.ino.
TASKPRIO [2/11]
#define TASKPRIO 10
Definition at line 2025 of file manyinone.ino.
TASKPRIO [3/11]
#define TASKPRIO 10
Definition at line 2025 of file manyinone.ino.
TASKPRIO [4/11]
#define TASKPRIO 10
Definition at line 2025 of file manyinone.ino.
TASKPRIO [5/11]
#define TASKPRIO 10
Definition at line 2025 of file manyinone.ino.
TASKPRIO [6/11]
#define TASKPRIO 10
Definition at line 2025 of file manyinone.ino.
TASKPRIO [7/11]
#define TASKPRIO 10
Definition at line 2025 of file manyinone.ino.
TASKPRIO [8/11]
#define TASKPRIO 10
Definition at line 2025 of file manyinone.ino.
TASKPRIO [9/11]
#define TASKPRIO 10
Definition at line 2025 of file manyinone.ino.
TASKPRIO [10/11]
#define TASKPRIO 10
Definition at line 2025 of file manyinone.ino.
TASKPRIO [11/11]
#define TASKPRIO 10
Definition at line 2025 of file manyinone.ino.
Function Documentation
getDataInCritRegion()
struct shDataTp getDataInCritRegion (void)
Definition at line 1932 of file manyinone.ino.
References shDataTp::counter, k_eat_msec(), k_signal(), k_wait(), semmutex, and sharedData.
k_breakout()
void k_breakout ()
Definition at line 78 of file manyinone.ino.
References k_t::nr, and pRun.
k_sem_clip()
void k_sem_clip (unsigned char nr, int i)
Definition at line 60 of file manyinone.ino.
References led13, and k_t::nr.
k_sem_unclip()
void k_sem_unclip (unsigned char nr)
Definition at line 67 of file manyinone.ino.
References led13, and k_t::nr.
loop()
void loop ()
Definition at line 50 of file manyinone.ino.
saveDataInCritRegion()
void saveDataInCritRegion (int v)
Definition at line 1905 of file manyinone.ino.
References shDataTp::counter, k_signal(), k_wait(), semmutex, sharedData, and shDataTp::v.
saveDataInCritRegionNoWait()
int saveDataInCritRegionNoWait (int v)
Definition at line 1916 of file manyinone.ino.
References shDataTp::counter, k_signal(), k_wait(), semmutex, sharedData, shDataTp::v, and x.
setup()
void setup ()
Definition at line 35 of file manyinone.ino.
References i, k_crt_task(), k_init(), k_start(), pTask, pTask2, stak, stak2, STKSIZE, task(), task2(), and TASKPRIO.
t1()
void t1 ()
Definition at line 1136 of file manyinone.ino.
References k_sleep().
t2()
void t2 (void)
Definition at line 1261 of file manyinone.ino.
References k_eat_msec().
task()
void task ()
Definition at line 15 of file manyinone.ino.
Referenced by setup().
task1()
void task1 ()
Definition at line 1784 of file manyinone.ino.
References er2, k_eat_msec(), k_set_sem_timer(), k_wait(), loopCnt, and s1.
task2()
void task2 ()
Definition at line 25 of file manyinone.ino.
Referenced by setup().
tgeneric()
void tgeneric ()
Definition at line 2315 of file manyinone.ino.
References k_eat_msec(), k_sleep(), k_t::nr, and pRun.
tnoise()
void tnoise ()
Definition at line 1609 of file manyinone.ino.
References k_eat_msec(), and k_sleep().
tperiodic()
void tperiodic ()
Definition at line 1580 of file manyinone.ino.
References k_t::clip, clipp, k_eat_msec(), k_set_sem_timer(), k_wait(), sem1, and x.
Variable Documentation
a1
char a1[STK]
Definition at line 1846 of file manyinone.ino.
a2
char a2[STK]
Definition at line 1846 of file manyinone.ino.
clipp
int clipp
Definition at line 1579 of file manyinone.ino.
Referenced by tperiodic().
dataBufForMsgQ
int dataBufForMsgQ[10]
Definition at line 2032 of file manyinone.ino.
er2
int er2
Definition at line 1783 of file manyinone.ino.
Referenced by task1().
err
int err
Definition at line 1617 of file manyinone.ino.
i
volatile int i = 0
Definition at line 1249 of file manyinone.ino.
Referenced by setup().
led13
unsigned char led13
Definition at line 59 of file manyinone.ino.
Referenced by k_sem_clip(), and k_sem_unclip().
loopCnt
int loopCnt = 0
Definition at line 1781 of file manyinone.ino.
Referenced by task1().
msgQ
struct k_msg_t* msgQ
Definition at line 2030 of file manyinone.ino.
mutSem
struct k_t * mutSem
Definition at line 2034 of file manyinone.ino.
noDataDelivered
volatile int noDataDelivered = 0
Definition at line 1902 of file manyinone.ino.
p1
struct k_t* p1
Definition at line 1438 of file manyinone.ino.
p2
struct k_t * p2
Definition at line 1438 of file manyinone.ino.
p3
struct k_t * p3
Definition at line 2129 of file manyinone.ino.
pendingWait
int pendingWait = 0
Definition at line 1781 of file manyinone.ino.
pt1
struct k_t* pt1
Definition at line 1243 of file manyinone.ino.
pt2
struct k_t * pt2
Definition at line 1244 of file manyinone.ino.
pTask
struct k_t* pTask
Definition at line 13 of file manyinone.ino.
Referenced by setup().
pTask1
struct k_t* pTask1
Definition at line 2028 of file manyinone.ino.
pTask2
struct k_t * pTask2
Definition at line 13 of file manyinone.ino.
Referenced by setup().
reg
volatile char reg = 0
Definition at line 287 of file manyinone.ino.
s1
struct k_t * s1
Definition at line 1441 of file manyinone.ino.
Referenced by task1().
s2
unsigned char s2[SS]
Definition at line 1441 of file manyinone.ino.
sem1
struct k_t * sem1
Definition at line 285 of file manyinone.ino.
Referenced by tperiodic().
sem2
struct k_t * sem2
Definition at line 888 of file manyinone.ino.
semmutex
struct k_t * semmutex
Definition at line 1892 of file manyinone.ino.
Referenced by getDataInCritRegion(), saveDataInCritRegion(), and saveDataInCritRegionNoWait().
sharedData
struct shDataTp sharedData = {0, 0}
Definition at line 1900 of file manyinone.ino.
Referenced by getDataInCritRegion(), saveDataInCritRegion(), and saveDataInCritRegionNoWait().
st1
char st1[STK]
Definition at line 1574 of file manyinone.ino.
st2
char st2[STK]
Definition at line 1574 of file manyinone.ino.
st3
char st3[STK]
Definition at line 2132 of file manyinone.ino.
stak
char stak[STKSIZE]
Definition at line 12 of file manyinone.ino.
Referenced by setup().
stak1
unsigned char stak1[STKSZ]
Definition at line 1246 of file manyinone.ino.
stak2
unsigned char stak2[STKSZ]
Definition at line 12 of file manyinone.ino.
Referenced by setup().
t2Hit
volatile int t2Hit = 0
Definition at line 2036 of file manyinone.ino.
t2Missed
volatile int t2Missed = 0
Definition at line 2036 of file manyinone.ino.
taskStak
unsigned char taskStak[STK]
Definition at line 1134 of file manyinone.ino.
timedSem1
struct k_t* timedSem1
Definition at line 2034 of file manyinone.ino.
timedSem2
struct k_t * timedSem2
Definition at line 2034 of file manyinone.ino.
tStart
unsigned long tStart
Definition at line 1520 of file manyinone.ino.
tStop
unsigned long tStop
Definition at line 1520 of file manyinone.ino.
x
int x = 0
Definition at line 1578 of file manyinone.ino.
Referenced by saveDataInCritRegionNoWait(), and tperiodic().