krnl: examples/oldobsolete/old-may-not_work/msgtstisrsimple/msgtstisrsimple.ino File Reference
msgtstisrsimple.ino File Reference
#include <krnl.h>
Macros
#define STK_SIZE 200
Functions
void doBlink (void)
void t1 (void)
void t2 (void)
ISR (INT0_vect, ISR_NAKED)
void installISR2 ()
void setup ()
void loop (void)
Variables
struct k_t * tSm1
struct k_t * tSm2
struct k_t * p_t1
struct k_t * p_t2
struct k_msg_t * pMsg
struct k_msg_t * pMsg2
char mar [10 *2]
char mar2 [10 *2]
char s1 [STK_SIZE]
char s2 [STK_SIZE]
volatile int icnt =0
Macro Definition Documentation
STK_SIZE
#define STK_SIZE 200
Definition at line 22 of file msgtstisrsimple.ino.
Function Documentation
doBlink()
void doBlink (void)
Definition at line 30 of file msgtstisrsimple.ino.
installISR2()
void installISR2 ()
Definition at line 81 of file msgtstisrsimple.ino.
ISR()
ISR (INT0_vect , ISR_NAKED)
Definition at line 63 of file msgtstisrsimple.ino.
References icnt, K_CHG_STAK, k_running, ki_send(), pMsg, PUSHREGS(), and RETI().
loop()
void loop (void)
Definition at line 126 of file msgtstisrsimple.ino.
setup()
void setup ()
Definition at line 99 of file msgtstisrsimple.ino.
References installISR2(), k_crt_sem(), k_crt_send_Q(), k_crt_task(), k_init(), k_start(), KRNL_VRS, mar, mar2, p_t1, p_t2, pMsg, pMsg2, s1, s2, STK_SIZE, t1(), t2(), tSm1, and tSm2.
t1()
void t1 (void)
Definition at line 36 of file msgtstisrsimple.ino.
References doBlink(), i, k_receive(), and pMsg2.
t2()
void t2 (void)
Definition at line 46 of file msgtstisrsimple.ino.
References i, k_receive(), k_send(), pMsg, and pMsg2.
Variable Documentation
icnt
volatile int icnt =0
Definition at line 27 of file msgtstisrsimple.ino.
mar
char mar[10 *2]
Definition at line 19 of file msgtstisrsimple.ino.
mar2
char mar2[10 *2]
Definition at line 20 of file msgtstisrsimple.ino.
p_t1
struct k_t* p_t1
Definition at line 16 of file msgtstisrsimple.ino.
p_t2
struct k_t * p_t2
Definition at line 16 of file msgtstisrsimple.ino.
pMsg
struct k_msg_t* pMsg
Definition at line 18 of file msgtstisrsimple.ino.
pMsg2
struct k_msg_t * pMsg2
Definition at line 18 of file msgtstisrsimple.ino.
s1
char s1[STK_SIZE]
Definition at line 24 of file msgtstisrsimple.ino.
s2
char s2[STK_SIZE]
Definition at line 25 of file msgtstisrsimple.ino.
tSm1
struct k_t* tSm1
Definition at line 15 of file msgtstisrsimple.ino.
tSm2
struct k_t * tSm2
Definition at line 15 of file msgtstisrsimple.ino.