krnl: examples/oldobsolete/old-may-not_work/k02simplecontroller/k02simplecontroller.ino File Reference
k02simplecontroller.ino File Reference
#include <krnl.h>
Functions
void toggleLED13 ()
void t1 (void)
void t2 (void)
void setup ()
void loop ()
Variables
struct k_t * pt1
struct k_t * pt2
struct k_t * samplingsSem
char s1 [200]
char s2 [200]
Function Documentation
loop()
void loop ()
Definition at line 95 of file k02simplecontroller.ino.
setup()
void setup ()
Definition at line 61 of file k02simplecontroller.ino.
References k_crt_sem(), k_crt_task(), k_init(), k_start(), pt1, pt2, s1, s2, samplingsSem, t1(), and t2().
t1()
void t1 (void)
Definition at line 28 of file k02simplecontroller.ino.
References k_set_sem_timer(), k_wait(), samplingsSem, and toggleLED13().
t2()
void t2 (void)
Definition at line 51 of file k02simplecontroller.ino.
References k_sleep().
toggleLED13()
void toggleLED13 ()
Definition at line 15 of file k02simplecontroller.ino.
Variable Documentation
pt1
struct k_t* pt1
Definition at line 8 of file k02simplecontroller.ino.
pt2
struct k_t * pt2
Definition at line 9 of file k02simplecontroller.ino.
s1
char s1[200]
Definition at line 12 of file k02simplecontroller.ino.
s2
char s2[200]
Definition at line 13 of file k02simplecontroller.ino.
samplingsSem
struct k_t * samplingsSem
Definition at line 10 of file k02simplecontroller.ino.