krnl: examples/oldobsolete/old-may-not_work/kernelmoviesimple/kernelmoviesimple.ino File Reference
kernelmoviesimple.ino File Reference
#include <krnl.h>
Functions
void taskBody ()
void setup ()
void loop ()
Variables
struct k_t * sem
struct k_t * task
char stak [100]
Function Documentation
loop()
void loop ()
Definition at line 32 of file kernelmoviesimple.ino.
setup()
void setup ()
Definition at line 21 of file kernelmoviesimple.ino.
References k_crt_sem(), k_crt_task(), k_init(), k_start(), sem, stak, task, and taskBody().
taskBody()
void taskBody ()
Definition at line 12 of file kernelmoviesimple.ino.
References k_wait(), and sem.
Variable Documentation
sem
struct k_t* sem
Definition at line 10 of file kernelmoviesimple.ino.
stak
char stak[100]
Definition at line 20 of file kernelmoviesimple.ino.
task
struct k_t * task
Definition at line 10 of file kernelmoviesimple.ino.