krnl: examples/oldobsolete/old-may-not_work/krnlgen/krnlgen.ino File Reference
krnlgen.ino File Reference
#include <krnl.h>
Macros
#define STK 150
Functions
void tcode1 ()
void tcode2 ()
void setup ()
void loop ()
Variables
struct k_t * t1
struct k_t * t2
struct k_t * s1
struct k_t * s2
struct k_msg_t * mq1
struct k_msg_t * mq2
char stk1 [STK]
char stk2 [STK]
Macro Definition Documentation
STK
#define STK 150
Definition at line 7 of file krnlgen.ino.
Function Documentation
loop()
void loop ()
Definition at line 40 of file krnlgen.ino.
setup()
void setup ()
Definition at line 26 of file krnlgen.ino.
References k_crt_sem(), k_crt_task(), k_init(), k_start(), s1, s2, STK, stk1, stk2, t1, t2, tcode1(), and tcode2().
tcode1()
void tcode1 ()
Definition at line 11 of file krnlgen.ino.
tcode2()
void tcode2 ()
Definition at line 18 of file krnlgen.ino.
Variable Documentation
mq1
struct k_msg_t* mq1
Definition at line 5 of file krnlgen.ino.
mq2
struct k_msg_t * mq2
Definition at line 5 of file krnlgen.ino.
s1
struct k_t * s1
Definition at line 3 of file krnlgen.ino.
s2
struct k_t * s2
Definition at line 3 of file krnlgen.ino.
stk1
char stk1[STK]
Definition at line 9 of file krnlgen.ino.
stk2
char stk2[STK]
Definition at line 9 of file krnlgen.ino.
t1
struct k_t* t1
Definition at line 3 of file krnlgen.ino.
t2
struct k_t * t2
Definition at line 3 of file krnlgen.ino.