krnl: examples/oldobsolete/old-may-not_work/kernelkick/kernelkick.ino File Reference
kernelkick.ino File Reference
#include <krnl.h>
Functions
void task1Body (void)
void task2Body (void)
void setup ()
void loop ()
Variables
struct k_t * syncSem
struct k_t * loopSem
struct k_t * ptask1
struct k_t * ptask2
char stak1 [100]
char stak2 [100]
Function Documentation
loop()
void loop ()
Definition at line 42 of file kernelkick.ino.
setup()
void setup ()
Definition at line 30 of file kernelkick.ino.
References k_crt_sem(), k_crt_task(), k_init(), k_start(), loopSem, ptask1, ptask2, stak1, stak2, syncSem, task1Body(), and task2Body().
task1Body()
void task1Body (void)
Definition at line 13 of file kernelkick.ino.
References k_wait(), and syncSem.
task2Body()
void task2Body (void)
Definition at line 21 of file kernelkick.ino.
References k_set_sem_timer(), k_signal(), k_wait(), loopSem, and syncSem.
Variable Documentation
loopSem
struct k_t * loopSem
Definition at line 9 of file kernelkick.ino.
ptask1
struct k_t * ptask1
Definition at line 9 of file kernelkick.ino.
ptask2
struct k_t * ptask2
Definition at line 9 of file kernelkick.ino.
stak1
char stak1[100]
Definition at line 11 of file kernelkick.ino.
stak2
char stak2[100]
Definition at line 11 of file kernelkick.ino.
syncSem
struct k_t* syncSem
Definition at line 9 of file kernelkick.ino.