krnl: examples/oldobsolete/old-may-not_work/akrnltaskblink3/akrnltaskblink3.ino File Reference
akrnltaskblink3.ino File Reference
#include <krnl.h>
Macros
#define TICKSPEED 10
#define STK 100
Functions
void highprio ()
void medprio ()
void lowprio ()
void setup ()
void loop ()
void k_sem_clip (unsigned char nr, int i)
void k_breakout ()
Variables
struct k_t * pt1
struct k_t * pt2
struct k_t * pt3
struct k_t * sem1
struct k_t * sem2
struct k_t * sem3
char st1 [STK]
char st2 [STK]
char st3 [STK]
volatile unsigned char led13 = 0
Macro Definition Documentation
STK
#define STK 100
Definition at line 35 of file akrnltaskblink3.ino.
TICKSPEED
#define TICKSPEED 10
Definition at line 33 of file akrnltaskblink3.ino.
Function Documentation
highprio()
void highprio ()
Definition at line 40 of file akrnltaskblink3.ino.
References k_t::clip, k_set_sem_timer(), k_wait(), sem1, and TICKSPEED.
k_breakout()
void k_breakout ()
Definition at line 110 of file akrnltaskblink3.ino.
References led13, k_t::nr, and pRun.
k_sem_clip()
void k_sem_clip (unsigned char nr, int i)
Definition at line 103 of file akrnltaskblink3.ino.
References led13.
loop()
void loop ()
Definition at line 96 of file akrnltaskblink3.ino.
lowprio()
void lowprio ()
Definition at line 62 of file akrnltaskblink3.ino.
References k_t::clip, k_set_sem_timer(), k_wait(), led13, sem3, and TICKSPEED.
medprio()
void medprio ()
Definition at line 52 of file akrnltaskblink3.ino.
References k_t::clip, k_set_sem_timer(), k_wait(), sem2, and TICKSPEED.
setup()
void setup ()
Definition at line 74 of file akrnltaskblink3.ino.
References highprio(), i, k_crt_sem(), k_crt_task(), k_init(), k_start(), lowprio(), medprio(), pt1, pt2, pt3, sem1, sem2, sem3, st1, st2, st3, and STK.
Variable Documentation
led13
volatile unsigned char led13 = 0
Definition at line 38 of file akrnltaskblink3.ino.
pt1
struct k_t* pt1
Definition at line 30 of file akrnltaskblink3.ino.
pt2
struct k_t * pt2
Definition at line 30 of file akrnltaskblink3.ino.
pt3
struct k_t * pt3
Definition at line 30 of file akrnltaskblink3.ino.
sem1
struct k_t * sem1
Definition at line 31 of file akrnltaskblink3.ino.
sem2
struct k_t * sem2
Definition at line 31 of file akrnltaskblink3.ino.
sem3
struct k_t * sem3
Definition at line 31 of file akrnltaskblink3.ino.
st1
char st1[STK]
Definition at line 36 of file akrnltaskblink3.ino.
st2
char st2[STK]
Definition at line 36 of file akrnltaskblink3.ino.
st3
char st3[STK]
Definition at line 36 of file akrnltaskblink3.ino.