krnl: examples/oldobsolete/old-may-not_work/krnlstaktstprint/krnlstaktstprint.ino File Reference
krnlstaktstprint.ino File Reference
#include <krnl.h>
Functions
void t1 ()
void setup ()
void loop ()
Variables
char s [150]
struct k_t * e
Function Documentation
loop()
void loop ()
Definition at line 27 of file krnlstaktstprint.ino.
setup()
void setup ()
Definition at line 19 of file krnlstaktstprint.ino.
References e, i, k_crt_task(), k_init(), k_start(), s, and t1().
t1()
void t1 ()
Definition at line 6 of file krnlstaktstprint.ino.
References e, i, j, and k_unused_stak().
Variable Documentation
e
struct k_t* e
Definition at line 5 of file krnlstaktstprint.ino.
s
char s[150]
Definition at line 4 of file krnlstaktstprint.ino.