krnl: examples/oldobsolete/old-may-not_work/debug/isem/isem.ino File Reference
isem.ino File Reference
#include <krnl.h>
Macros
#define STK_SIZE 400
Functions
void doBlink (void)
void t1 (void)
ISR (INT0_vect, ISR_NAKED)
void initISR ()
void setup ()
void loop (void)
Variables
struct k_t * p_t1
struct k_t * sem1
char s1 [STK_SIZE]
volatile int icnt =0
Macro Definition Documentation
STK_SIZE
#define STK_SIZE 400
Definition at line 17 of file isem.ino.
Function Documentation
doBlink()
void doBlink (void)
Definition at line 24 of file isem.ino.
initISR()
void initISR ()
Definition at line 64 of file isem.ino.
ISR()
ISR (INT0_vect , ISR_NAKED)
Definition at line 47 of file isem.ino.
References icnt, K_CHG_STAK, k_running, ki_signal(), PUSHREGS(), RETI(), and sem1.
loop()
void loop (void)
Definition at line 101 of file isem.ino.
setup()
void setup ()
Definition at line 81 of file isem.ino.
References initISR(), k_crt_sem(), k_crt_task(), k_init(), k_start(), p_t1, s1, sem1, STK_SIZE, and t1().
t1()
void t1 (void)
Definition at line 32 of file isem.ino.
References doBlink(), i, k_wait(), and sem1.
Variable Documentation
icnt
volatile int icnt =0
Definition at line 22 of file isem.ino.
p_t1
struct k_t* p_t1
Definition at line 15 of file isem.ino.
s1
char s1[STK_SIZE]
Definition at line 19 of file isem.ino.
sem1
struct k_t * sem1
Definition at line 15 of file isem.ino.