krnl: examples/oldobsolete/old-may-not_work/semsync/semsync.ino File Reference
semsync.ino File Reference
#include <krnl.h>
Functions
void doBlink (void)
void t1 (void)
void t2 (void)
void setup ()
void loop ()
Variables
struct k_t * pt1
struct k_t * sem1
char s1 [200]
struct k_t * pt2
char s2 [200]
Function Documentation
doBlink()
void doBlink (void)
Definition at line 8 of file semsync.ino.
loop()
void loop ()
Definition at line 45 of file semsync.ino.
setup()
void setup ()
Definition at line 34 of file semsync.ino.
References k_crt_sem(), k_crt_task(), k_init(), k_start(), pt1, pt2, s1, s2, sem1, t1(), and t2().
t1()
void t1 (void)
Definition at line 14 of file semsync.ino.
References doBlink(), i, k_wait(), and sem1.
t2()
void t2 (void)
Definition at line 26 of file semsync.ino.
References k_signal(), k_sleep(), and sem1.
Variable Documentation
pt1
struct k_t* pt1
Definition at line 3 of file semsync.ino.
pt2
struct k_t* pt2
Definition at line 5 of file semsync.ino.
s1
char s1[200]
Definition at line 4 of file semsync.ino.
s2
char s2[200]
Definition at line 6 of file semsync.ino.
sem1
struct k_t * sem1
Definition at line 3 of file semsync.ino.