krnl: examples/oldobsolete/rt-arduino-isrsendmsg/rt-arduino-isrsendmsg.ino File Reference
rt-arduino-isrsendmsg.ino File Reference
#include <krnl.h>
Macros
#define STK 150
#define TASKPRIO 10
Functions
ISR (INT4_vect, ISR_NAKED)
void task1 ()
void setup ()
void loop ()
Variables
struct k_t * pTask1
struct k_msg_t * msgQ
const int BUFSZ = 10
int bufForQ [BUFSZ]
volatile int ISRoverflow = 0
volatile int nrISR = 0
volatile unsigned long last = 0
Macro Definition Documentation
STK
#define STK 150
Definition at line 7 of file rt-arduino-isrsendmsg.ino.
TASKPRIO
#define TASKPRIO 10
Definition at line 9 of file rt-arduino-isrsendmsg.ino.
Function Documentation
ISR()
ISR (INT4_vect , ISR_NAKED)
Definition at line 27 of file rt-arduino-isrsendmsg.ino.
References K_CHG_STAK, k_running, ki_send(), msgQ, nrISR, PUSHREGS(), and RETI().
loop()
void loop ()
Definition at line 105 of file rt-arduino-isrsendmsg.ino.
setup()
void setup ()
Definition at line 64 of file rt-arduino-isrsendmsg.ino.
References bufForQ, BUFSZ, k_crt_send_Q(), k_crt_task(), k_init(), k_start(), msgQ, pTask1, STK, and task1().
task1()
void task1 ()
Definition at line 43 of file rt-arduino-isrsendmsg.ino.
References k_receive(), msgQ, and t.
Referenced by setup().
Variable Documentation
bufForQ
int bufForQ[BUFSZ]
Definition at line 16 of file rt-arduino-isrsendmsg.ino.
Referenced by setup().
BUFSZ
const int BUFSZ = 10
Definition at line 14 of file rt-arduino-isrsendmsg.ino.
Referenced by setup().
ISRoverflow
volatile int ISRoverflow = 0
Definition at line 21 of file rt-arduino-isrsendmsg.ino.
last
volatile unsigned long last = 0
Definition at line 25 of file rt-arduino-isrsendmsg.ino.
msgQ
struct k_msg_t* msgQ
Definition at line 13 of file rt-arduino-isrsendmsg.ino.
Referenced by ISR(), setup(), and task1().
nrISR
volatile int nrISR = 0
Definition at line 23 of file rt-arduino-isrsendmsg.ino.
Referenced by ISR().
pTask1
struct k_t* pTask1
Definition at line 12 of file rt-arduino-isrsendmsg.ino.
Referenced by setup().