krnl: examples/oldobsolete/rt-arduino-rdwr/rt-arduino-rdwr.ino File Reference
rt-arduino-rdwr.ino File Reference
#include <krnl.h>
Functions
void wr (void)
void rd (void)
void setup ()
void loop ()
Variables
struct k_rwlock_t lock1
volatile int rdNr = 0
Function Documentation
loop()
void loop ()
Definition at line 55 of file rt-arduino-rdwr.ino.
rd()
void rd (void)
Definition at line 24 of file rt-arduino-rdwr.ino.
References k_eat_ticks(), k_sleep(), lock1, and rdNr.
Referenced by setup().
setup()
void setup ()
Definition at line 40 of file rt-arduino-rdwr.ino.
References k_crt_task(), k_init(), k_start(), lock1, rd(), and wr().
wr()
void wr (void)
Definition at line 10 of file rt-arduino-rdwr.ino.
References i, k_eat_ticks(), k_sleep(), and lock1.
Referenced by setup().
Variable Documentation
lock1
struct k_rwlock_t lock1
Definition at line 7 of file rt-arduino-rdwr.ino.
Referenced by rd(), setup(), and wr().
rdNr
volatile int rdNr = 0
Definition at line 23 of file rt-arduino-rdwr.ino.
Referenced by rd().