krnl: examples/oldobsolete/rt-arduino-reader-writerf/rt-arduino-reader-writerf.ino File Reference
rt-arduino-reader-writerf.ino File Reference
#include <krnl.h>
Data Structures
struct rdWrLockTp
Functions
int rdWrLockInit (struct rdWrLockTp *lock)
void rdEnter (struct rdWrLockTp *lock)
void wrEnter (struct rdWrLockTp *lock)
void wrLeave (struct rdWrLockTp *lock)
void rdLeave (struct rdWrLockTp *lock)
void wr (void)
void rd (void)
void setup ()
void loop ()
Variables
struct rdWrLockTp rdWrLock1
volatile int rdInsideFortest = 0
volatile int rdNr = 0
Function Documentation
loop()
void loop ()
Definition at line 113 of file rt-arduino-reader-writerf.ino.
rd()
void rd (void)
Definition at line 82 of file rt-arduino-reader-writerf.ino.
References k_eat_ticks(), k_sleep(), rdEnter(), rdLeave(), rdNr, and rdWrLock1.
Referenced by setup().
rdEnter()
void rdEnter (struct rdWrLockTp * lock)
Definition at line 28 of file rt-arduino-reader-writerf.ino.
References rdWrLockTp::fifoSem, k_signal(), k_wait(), rdWrLockTp::rdCount, rdWrLockTp::rdSem, and rdWrLockTp::wrSem.
Referenced by rd().
rdLeave()
void rdLeave (struct rdWrLockTp * lock)
Definition at line 53 of file rt-arduino-reader-writerf.ino.
References k_signal(), k_wait(), rdWrLockTp::rdCount, rdInsideFortest, rdWrLockTp::rdSem, and rdWrLockTp::wrSem.
Referenced by rd().
rdWrLockInit()
int rdWrLockInit (struct rdWrLockTp * lock)
Definition at line 19 of file rt-arduino-reader-writerf.ino.
References rdWrLockTp::fifoSem, k_crt_sem(), rdWrLockTp::rdCount, rdWrLockTp::rdSem, and rdWrLockTp::wrSem.
Referenced by setup().
setup()
void setup ()
Definition at line 98 of file rt-arduino-reader-writerf.ino.
References k_crt_task(), k_init(), k_start(), rd(), rdWrLock1, rdWrLockInit(), and wr().
wr()
void wr (void)
Definition at line 65 of file rt-arduino-reader-writerf.ino.
References i, k_eat_ticks(), k_sleep(), rdInsideFortest, rdWrLock1, wrEnter(), and wrLeave().
Referenced by setup().
wrEnter()
void wrEnter (struct rdWrLockTp * lock)
Definition at line 41 of file rt-arduino-reader-writerf.ino.
References rdWrLockTp::fifoSem, k_signal(), k_wait(), and rdWrLockTp::wrSem.
Referenced by wr().
wrLeave()
void wrLeave (struct rdWrLockTp * lock)
Definition at line 48 of file rt-arduino-reader-writerf.ino.
References k_signal(), and rdWrLockTp::wrSem.
Referenced by wr().
Variable Documentation
rdInsideFortest
volatile int rdInsideFortest = 0
Definition at line 15 of file rt-arduino-reader-writerf.ino.
Referenced by rdLeave(), and wr().
rdNr
volatile int rdNr = 0
Definition at line 81 of file rt-arduino-reader-writerf.ino.
Referenced by rd().
rdWrLock1
struct rdWrLockTp rdWrLock1
Definition at line 13 of file rt-arduino-reader-writerf.ino.
Referenced by rd(), setup(), and wr().