krnl: examples/oldobsolete/old/semmutex/semmutex.ino File Reference
semmutex.ino File Reference
#include <krnl.h>
Functions
void t1Code ()
void t2Code ()
void setup ()
void loop ()
Variables
struct k_t * t1
struct k_t * t2
struct k_t * mutexSem
char stak1 [100]
char stak2 [100]
Function Documentation
loop()
void loop ()
Definition at line 45 of file semmutex.ino.
setup()
void setup ()
Definition at line 36 of file semmutex.ino.
References k_crt_sem(), k_crt_task(), k_init(), k_start(), mutexSem, stak1, stak2, t1, t1Code(), t2, and t2Code().
t1Code()
void t1Code ()
Definition at line 13 of file semmutex.ino.
References k_signal(), k_wait(), and mutexSem.
Referenced by setup().
t2Code()
void t2Code ()
Definition at line 24 of file semmutex.ino.
References k_signal(), k_wait(), and mutexSem.
Referenced by setup().
Variable Documentation
mutexSem
struct k_t * mutexSem
Definition at line 9 of file semmutex.ino.
Referenced by setup(), t1Code(), and t2Code().
stak1
char stak1[100]
Definition at line 11 of file semmutex.ino.
Referenced by setup().
stak2
char stak2[100]
Definition at line 11 of file semmutex.ino.
Referenced by setup().
t1
struct k_t* t1
Definition at line 9 of file semmutex.ino.
Referenced by setup().
t2
struct k_t * t2
Definition at line 9 of file semmutex.ino.
Referenced by setup().