krnl: examples/oldobsolete/old/semperf/semperf.ino File Reference
semperf.ino File Reference
#include <krnl.h>
Functions
void t1 (void)
void t2 (void)
void setup ()
void loop ()
Variables
struct k_t * pt1
struct k_t * sem1
char s1 [200]
struct k_t * pt2
char s2 [200]
Function Documentation
loop()
void loop ()
Definition at line 58 of file semperf.ino.
setup()
void setup ()
Definition at line 45 of file semperf.ino.
References i, k_crt_sem(), k_crt_task(), k_init(), k_start(), pt1, pt2, s1, s2, sem1, t1(), and t2().
t1()
void t1 (void)
Definition at line 16 of file semperf.ino.
References k_signal(), and sem1.
Referenced by setup().
t2()
void t2 (void)
Definition at line 23 of file semperf.ino.
References i, k_wait(), and sem1.
Referenced by setup().
Variable Documentation
pt1
struct k_t* pt1
Definition at line 11 of file semperf.ino.
Referenced by setup().
pt2
struct k_t* pt2
Definition at line 13 of file semperf.ino.
Referenced by setup().
s1
char s1[200]
Definition at line 12 of file semperf.ino.
Referenced by setup().
s2
char s2[200]
Definition at line 14 of file semperf.ino.
Referenced by setup().
sem1
struct k_t * sem1
Definition at line 11 of file semperf.ino.
Referenced by setup(), t1(), and t2().