krnl: examples/nokrnl/time07/time07.ino File Reference
time07.ino File Reference
Functions
void setup ()
void controlCode1 ()
void controlCode2 ()
void loop ()
Variables
const unsigned long tPer1 = 300
const unsigned long tPer2 = 500
volatile unsigned long nextTimeToRun1 = 0
volatile unsigned long nextTimeToRun2 = 0
unsigned long t
Function Documentation
controlCode1()
void controlCode1 ()
Definition at line 17 of file time07.ino.
Referenced by loop().
controlCode2()
void controlCode2 ()
Definition at line 24 of file time07.ino.
Referenced by loop().
loop()
void loop ()
Definition at line 32 of file time07.ino.
References controlCode1(), controlCode2(), nextTimeToRun1, nextTimeToRun2, t, tPer1, and tPer2.
setup()
void setup ()
Definition at line 11 of file time07.ino.
Variable Documentation
nextTimeToRun1
volatile unsigned long nextTimeToRun1 = 0
Definition at line 8 of file time07.ino.
Referenced by loop().
nextTimeToRun2
volatile unsigned long nextTimeToRun2 = 0
Definition at line 8 of file time07.ino.
Referenced by loop().
t
unsigned long t
Definition at line 30 of file time07.ino.
Referenced by loop().
tPer1
const unsigned long tPer1 = 300
Definition at line 7 of file time07.ino.
Referenced by loop().
tPer2
const unsigned long tPer2 = 500
Definition at line 7 of file time07.ino.
Referenced by loop().