krnl: examples/nokrnl/time08/time08.ino File Reference
time08.ino File Reference
Functions
void setup ()
void controlCode1 ()
void controlCode2 ()
int kicker (void(*f)(), unsigned long *t, unsigned long per)
void loop ()
Variables
const unsigned long tPer1 = 300
const unsigned long tPer2 = 500
volatile unsigned long nextTimeToRun1 = 0
volatile unsigned long nextTimeToRun2 = 0
unsigned long tt
Function Documentation
controlCode1()
void controlCode1 ()
Definition at line 15 of file time08.ino.
Referenced by loop().
controlCode2()
void controlCode2 ()
Definition at line 26 of file time08.ino.
Referenced by loop().
kicker()
int kicker (void(*)() f, unsigned long * t, unsigned long per)
Definition at line 64 of file time08.ino.
References t, and tt.
Referenced by loop().
loop()
void loop ()
Definition at line 75 of file time08.ino.
References controlCode1(), controlCode2(), kicker(), nextTimeToRun1, nextTimeToRun2, tPer1, tPer2, and tt.
setup()
void setup ()
Definition at line 6 of file time08.ino.
Variable Documentation
nextTimeToRun1
volatile unsigned long nextTimeToRun1 = 0
Definition at line 12 of file time08.ino.
Referenced by loop().
nextTimeToRun2
volatile unsigned long nextTimeToRun2 = 0
Definition at line 12 of file time08.ino.
Referenced by loop().
tPer1
const unsigned long tPer1 = 300
Definition at line 10 of file time08.ino.
Referenced by loop().
tPer2
const unsigned long tPer2 = 500
Definition at line 11 of file time08.ino.
Referenced by loop().
tt
unsigned long tt
Definition at line 61 of file time08.ino.
Referenced by kicker(), and loop().